### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by OctAg0nO** [byt3bl33d3r/MITMf#122]
python mitmf.py -i wlan0 --hsts --arp --spoof --gateway 10.1.0.1
```
Exception happened during processing of request from ('10.1.0.1
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in proce
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finis
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __ini
    self.handle()
  File "/root/MITMf/core/servers/dns/DNSchef.py", line 376, in 
    response = self.parse(data)
  File "/root/MITMf/core/servers/dns/DNSchef.py", line 107, in 
    response = self.hstsbypass(qname[3:], qname, nameservers, d
  File "/root/MITMf/core/servers/dns/DNSchef.py", line 359, in 
    dns_rr = DNSRecord.parse(r).rr
  File "/usr/local/lib/python2.7/dist-packages/mitmflib/dnslib/
    buffer = DNSBuffer(packet)
  File "/usr/local/lib/python2.7/dist-packages/mitmflib/dnslib/
    super(DNSBuffer,self).__init__(data)
  File "/usr/local/lib/python2.7/dist-packages/mitmflib/dnslib/
    self.data = bytearray(data)
TypeError: 'NoneType' object is not iterable
```

**Comment by TadeoArmenta** [comment]
confirmed on kali
after that, it keeps working for a while  and then :

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 586, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 199, in doRead
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 413, in dataReceived
    self._flushReceiveBIO()
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 383, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 118, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 564, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 448, in lineReceived
    self.extractHeader(self._header)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 407, in extractHeader
    self.handleHeader(key, val)
  File "/usr/share/mitmf/core/sslstrip/SSLServerConnection.py", line 78, in handleHeader
    ServerConnection.handleHeader(self, key, value)
  File "/usr/share/mitmf/core/sslstrip/ServerConnection.py", line 146, in handleHeader
    mitmf_logger.info("{} [type:{}-{} os:{}] Zapped a strict-trasport-security header".format(self.client.getClientIP(), self.clientInfo[0], self.clientInfo[1], self.clientInfo[2]))
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'


and stop working

**Comment by byt3bl33d3r** [comment]
@OctAg0nO @TadeoArmenta can you please append ```--log debug``` to your command string and paste the output? 
Thanks

**Comment by TadeoArmenta** [comment]
http://pastebin.com/UfSEhTbQ

**Comment by byt3bl33d3r** [comment]
@TadeoArmenta thanks, these seem like to different errors actually waiting on @OctAg0nO to post the debug log, in the meantime i'll get to fixing this one today

**Comment by byt3bl33d3r** [comment]
@TadeoArmenta ok this should fix the bug you reported! thanks!

**Comment by TadeoArmenta** [comment]
@byt3bl33d3r  indeed it is fixed now, many thanks for your hard work

**Comment by OctAg0nO** [comment]
I reinstall a fresh copy of kali, i dont get the error anymore.

**Comment by byt3bl33d3r** [comment]
@OctAg0nO ok, it was probably a malformed DNS requests , if it happens again just comment below
