### ISSUE TITLE
Crash run MITMf in debian 8.0 jessie.

### ISSUE THREAD

**Issue by zirou30** [byt3bl33d3r/MITMf#136]
have idea this is problem?
I step by step instruction instalation run other_setup.sh to run mitmf th problem down:

root@Zirou:/home/Glaucio/hk/mitm/MITMf# python mitmf.py 
Traceback (most recent call last):
  File "mitmf.py", line 32, in <module>
    from plugins import *
  File "/home/Glaucio/hk/mitm/MITMf/plugins/FerretNG.py", line 31, in <module>
    from core.ferretng.FerretProxy import FerretProxy
  File "/home/Glaucio/hk/mitm/MITMf/core/ferretng/FerretProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/home/Glaucio/hk/mitm/MITMf/core/ferretng/ClientRequest.py", line 30, in <module>
    from twisted.internet import ssl
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 223, in <module>
    from twisted.internet._sslverify import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 192, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation(OpenSSL)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 167, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/usr/local/lib/python2.7/dist-packages/service_identity/__init__.py", line 12, in <module>
    from . import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 14, in <module>
    from ._common import (
  File "/usr/local/lib/python2.7/dist-packages/service_identity/_common.py", line 136, in <module>
    @attributes(["pattern"], apply_with_init=False)
TypeError: attributes() got an unexpected keyword argument 'apply_with_init'
root@Zirou:/home/Glaucio/hk/mitm/MITMf#

**Comment by byt3bl33d3r** [comment]
@zirou30 hi,
you seem to have a problem with Twisted, try re-downloading it via pip or use virtualenv.

**Comment by zirou30** [comment]
Thank you @byt3bl33d3r.
Amazingly I was in trouble in sslstrip, which had the following problem: sslstrip

Traceback (most recent call last):
  File "/ usr / bin / sslstrip", line 30, in <module>
    from sslstrip.StrippingProxy import StrippingProxy
  File "/usr/share/sslstrip/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/usr/share/sslstrip/sslstrip/ClientRequest.py", line 25, in <module>
    from twisted.internet import ssl
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 223, in <module>
    from twisted.internet._sslverify import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 192, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation (OpenSSL)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 167, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/usr/local/lib/python2.7/dist-packages/service_identity/__init__.py", line 12, in <module>
    from. pyOpenSSL import
  File "/usr/local/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 14, in <module>
    from ._common import (
  File "/usr/local/lib/python2.7/dist-packages/service_identity/_common.py", line 136, in <module>
    attributes (["pattern"] apply_with_init = False)
TypeError: attributes () got an unexpected keyword argument 'apply_with_init'

and seeking a solution to the problem, I realized that the pip has a library for sslstrip. As the site https://pypi.python.org/pypi/sslstrip/0.9.2 efetuei the installation and bingo worked for both sslstrip when to mitmf. 

./mitmf.py 

 ███▄ ▄███▓ ██▓▄▄▄█████▓ ███▄ ▄███▓  █████▒
▓██▒▀█▀ ██▒▓██▒▓  ██▒ ▓▒▓██▒▀█▀ ██▒▓██   ▒ 
▓██    ▓██░▒██▒▒ ▓██░ ▒░▓██    ▓██░▒████ ░ 
▒██    ▒██ ░██░░ ▓██▓ ░ ▒██    ▒██ ░▓█▒  ░ 
▒██▒   ░██▒░██░  ▒██▒ ░ ▒██▒   ░██▒░▒█░    
░ ▒░   ░  ░░▓    ▒ ░░   ░ ▒░   ░  ░ ▒ ░    
░  ░      ░ ▒ ░    ░    ░  ░      ░ ░      
░      ░    ▒ ░  ░      ░      ░    ░ ░    
       ░    ░                  ░                                                     

usage: mitmf.py -i interface [mitmf options] [plugin name] [plugin options]

MITMf v0.9.7 - Framework for MITM attacks

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit

MITMf:
  Options for MITMf

  --log-level {debug,info}

perfect @byt3bl33d3r thank you very much.

**Comment by zirou30** [comment]
Sorry my english @byt3bl33d3r

**Comment by byt3bl33d3r** [comment]
@zirou30 np, glad you resolved the issue!
