### ISSUE TITLE
screenshotter doesnt work

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#144]
it set --screen with and without --interval and get this
|_ ScreenShotter v0.4
Traceback (most recent call last):
  File "./mitmf.py", line 112, in <module>
    plugin.initialize(options)
  File "/root/MITMf/plugins/screenshotter.py", line 37, in initialize
    self.js_payload = self.get_payload()
  File "/root/MITMf/plugins/screenshotter.py", line 56, in get_payload
    return re.sub("SECONDS_GO_HERE", str(self.interval*1000), open("./core/javascript/screenshot.js", "rb").read())
AttributeError: 'ScreenShotter' object has no attribute 'interval'

**Comment by byt3bl33d3r** [comment]
@WiredLife thanks, should be fixed now
