### ISSUE TITLE
upsidedownternet doesnt work

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#146]
after a client visits a website
```python
2015-08-02 22:00:44 192.168.178.241 [type:Chrome-44 os:Windows 7] images1.test.de
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 850, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
KeyError: 'clientip'
Logged from file upsidedownternet.py, line 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 850, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
KeyError: 'clientip'
Logged from file upsidedownternet.py, line 59
```

**Comment by byt3bl33d3r** [comment]
@WiredLife oops , forgot to backport some changes to that module, thanks will fix later today

**Comment by byt3bl33d3r** [comment]
@WiredLife this should be fixed now, will merge to master soon

**Comment by WiredLife** [comment]
waiting for merge ;)

**Comment by byt3bl33d3r** [comment]
@WiredLife just merged it now
