### ISSUE TITLE
missing settings in mitmf.conf

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#149]
after current update i miss the settings for the http and smb port
so i get
Error starting HTTP server: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/root/MITMf/core/servers/HTTP.py", line 54, in start
    server = ThreadingTCPServer((settings.Config.Bind_To, 80), HTTP1)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/root/MITMf/core/servers/HTTP.py", line 76, in server_bind
    TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
|_ HTTP server online
|_ DNSChef v0.4 online
Error starting SMB server: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/root/MITMf/core/servers/SMB.py", line 33, in start
    server1 = ThreadingTCPServer((settings.Config.Bind_To, 445), SMB1)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/root/MITMf/core/servers/SMB.py", line 57, in server_bind
    TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

**Comment by byt3bl33d3r** [comment]
the settings were removed because they were useless, don't think there would be any good reason to change the HTTP and SMB server ports, plus many plugins depend on them being on the default ports.

The error you're getting is because you have running services  on those ports so the servers can't bind to them

**Comment by WiredLife** [comment]
i know
so you recommend only the default ports?
then this ticket can be closed

**Comment by byt3bl33d3r** [comment]
I already closed it... many attacks/plugins wouldn't work if you changed the default ports

**Comment by theparadoxer02** [comment]
getting the same error
`Error starting HTTP server: [Errno 98] Address already in use`
 even after running the commands to close the port!
