### ISSUE TITLE
Requirements not all installing on fresh Kali 2.0 (64-bit)

### ISSUE THREAD

**Issue by vapor99** [byt3bl33d3r/MITMf#159]
I followed the instructions to the T, and been using mitmf for a long time on earlier Kali distros.  It seems the cryptography library doesn't want to get updated.  I have a fresh install of Kali 2.0 (64-bit) and latest git clone.  Output is below when doing a pip update:
```
pip install --upgrade -r requirements.txt
Downloading/unpacking git+git://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
  Cloning git://github.com/kti/python-netfilterqueue to /tmp/pip-uj_tGj-build
  Running setup.py (path:/tmp/pip-uj_tGj-build/setup.py) egg_info for package from git+git://github.com/kti/python-netfilterqueue

Downloading/unpacking git+git://github.com/gorakhargosh/watchdog (from -r requirements.txt (line 2))
  Cloning git://github.com/gorakhargosh/watchdog to /tmp/pip-9iMzrp-build
  Running setup.py (path:/tmp/pip-9iMzrp-build/setup.py) egg_info for package from git+git://github.com/gorakhargosh/watchdog

    warning: no files found matching '*.h' under directory 'src'
Requirement already up-to-date: pycrypto>=2.6 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Downloading/unpacking cryptography from https://pypi.python.org/packages/source/c/cryptography/cryptography-1.0.tar.gz#md5=3f2608eb94dcc6e616c3cc2e182181b0 (from -r requirements.txt (line 5))
  Downloading cryptography-1.0.tar.gz (331kB): 331kB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/cryptography/setup.py) egg_info for package cryptography

    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking Pillow from https://pypi.python.org/packages/source/P/Pillow/Pillow-2.9.0.tar.gz#md5=46f1729ece27981d54ec543ad5b37d14 (from -r requirements.txt (line 6))
  Downloading Pillow-2.9.0.tar.gz (9.3MB): 9.3MB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/Pillow/setup.py) egg_info for package Pillow

Downloading/unpacking netaddr from https://pypi.python.org/packages/any/n/netaddr/netaddr-0.7.15-py2.py3-none-any.whl#md5=8dff79790703c51d8472c98c61e64357 (from -r requirements.txt (line 7))
  Downloading netaddr-0.7.15-py2.py3-none-any.whl (1.5MB): 1.5MB downloaded
Downloading/unpacking scapy from https://pypi.python.org/packages/source/s/scapy/scapy-2.3.1.zip#md5=1527f09562d9c1bafa5e619c7782d5a0 (from -r requirements.txt (line 8))
  Downloading scapy-2.3.1.zip (1.1MB): 1.1MB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/scapy/setup.py) egg_info for package scapy

Downloading/unpacking dnslib (from -r requirements.txt (line 9))
  Downloading dnslib-0.9.4.tar.gz (59kB): 59kB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/dnslib/setup.py) egg_info for package dnslib

Downloading/unpacking Twisted from https://pypi.python.org/packages/source/T/Twisted/Twisted-15.3.0.tar.bz2#md5=b58e83da2f00b3352afad74d0c5c4599 (from -r requirements.txt (line 10))
  Downloading Twisted-15.3.0.tar.bz2 (4.4MB): 4.4MB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/Twisted/setup.py) egg_info for package Twisted

Downloading/unpacking pefile from https://pypi.python.org/packages/source/p/pefile/pefile-1.2.10-114.tar.gz#md5=c41988b09a9d68610387074f74d8523d (from -r requirements.txt (line 11))
  Downloading pefile-1.2.10-114.tar.gz (49kB): 49kB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/pefile/setup.py) egg_info for package pefile

Downloading/unpacking ipy from https://pypi.python.org/packages/source/I/IPy/IPy-0.83.tar.gz#md5=7b8c6eb4111b15aea31b67108e769712 (from -r requirements.txt (line 12))
  Downloading IPy-0.83.tar.gz
  Running setup.py (path:/tmp/pip-build-yaWNFu/ipy/setup.py) egg_info for package ipy

Downloading/unpacking user-agents (from -r requirements.txt (line 13))
  Downloading user-agents-0.3.2.tar.gz
  Running setup.py (path:/tmp/pip-build-yaWNFu/user-agents/setup.py) egg_info for package user-agents

Requirement already up-to-date: pyopenssl in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Downloading/unpacking service-identity from https://pypi.python.org/packages/2.7/s/service_identity/service_identity-14.0.0-py2.py3-none-any.whl#md5=8650917484fb4ef6132b177cb1165307 (from -r requirements.txt (line 15))
  Downloading service_identity-14.0.0-py2.py3-none-any.whl
Requirement already up-to-date: configobj in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already up-to-date: Flask in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already up-to-date: dnspython in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Downloading/unpacking beautifulsoup4 from https://pypi.python.org/packages/2.7/b/beautifulsoup4/beautifulsoup4-4.4.0-py2-none-any.whl#md5=c108fc02b9b31bc81f42bc90768edd66 (from -r requirements.txt (line 19))
  Downloading beautifulsoup4-4.4.0-py2-none-any.whl (81kB): 81kB downloaded
Downloading/unpacking capstone from https://pypi.python.org/packages/source/c/capstone/capstone-3.0.4.tar.gz#md5=3437fa632c89531a7d800a3f8c04fbe3 (from -r requirements.txt (line 20))
  Downloading capstone-3.0.4.tar.gz (3.2MB): 3.2MB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/capstone/setup.py) egg_info for package capstone

Downloading/unpacking python-magic (from -r requirements.txt (line 21))
  Downloading python-magic-0.4.6.tar.gz
  Running setup.py (path:/tmp/pip-build-yaWNFu/python-magic/setup.py) egg_info for package python-magic

Downloading/unpacking msgpack-python from https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.6.tar.gz#md5=8b317669314cf1bc881716cccdaccb30 (from -r requirements.txt (line 22))
  Downloading msgpack-python-0.4.6.tar.gz (116kB): 116kB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/msgpack-python/setup.py) egg_info for package msgpack-python

Requirement already up-to-date: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 23))
Downloading/unpacking pypcap (from -r requirements.txt (line 24))
  Downloading pypcap-1.1.3.tar.gz (44kB): 44kB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/pypcap/setup.py) egg_info for package pypcap
    Found pcap headers in /usr/include/pcap/pcap.h
    Found libraries in /usr/lib/x86_64-linux-gnu/libpcap.a
    No pcap-int.h found
    found pcap_setdirection
    found pcap_setnonblock
    found pcap_compile_nopcap function
    found pcap_file function

Requirement already up-to-date: PyYAML>=3.10 in /usr/lib/python2.7/dist-packages (from watchdog==0.8.3->-r requirements.txt (line 2))
Downloading/unpacking argh>=0.24.1 (from watchdog==0.8.3->-r requirements.txt (line 2))
  Downloading argh-0.26.1.tar.gz
  Running setup.py (path:/tmp/pip-build-yaWNFu/argh/setup.py) egg_info for package argh

Downloading/unpacking pathtools>=0.1.1 (from watchdog==0.8.3->-r requirements.txt (line 2))
  Downloading pathtools-0.1.2.tar.gz
  Running setup.py (path:/tmp/pip-build-yaWNFu/pathtools/setup.py) egg_info for package pathtools

Requirement already up-to-date: idna>=2.0 in /usr/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 5))
Downloading/unpacking six>=1.4.1 from https://pypi.python.org/packages/3.3/s/six/six-1.9.0-py2.py3-none-any.whl#md5=9ac7e129a80f72d6fc1f0216f6e9627b (from cryptography->-r requirements.txt (line 5))
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-18.1-py2.py3-none-any.whl#md5=b6c8eae6b3636dd952e71135805ee156 (from cryptography->-r requirements.txt (line 5))
  Downloading setuptools-18.1-py2.py3-none-any.whl (461kB): 461kB downloaded
Downloading/unpacking enum34 from https://pypi.python.org/packages/source/e/enum34/enum34-1.0.4.tar.gz#md5=ac80f432ac9373e7d162834b264034b6 (from cryptography->-r requirements.txt (line 5))
  Downloading enum34-1.0.4.tar.gz
  Running setup.py (path:/tmp/pip-build-yaWNFu/enum34/setup.py) egg_info for package enum34

Requirement already up-to-date: ipaddress in /usr/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 5))
Downloading/unpacking cffi>=1.1.0 (from cryptography->-r requirements.txt (line 5))
  Downloading cffi-1.1.2.tar.gz (326kB): 326kB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/cffi/setup.py) egg_info for package cffi

Downloading/unpacking zope.interface>=3.6.0 from https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.2.tar.gz#md5=04298faeaa70b4f3b23fa2ae8987262c (from Twisted->-r requirements.txt (line 10))
  Downloading zope.interface-4.1.2.tar.gz (919kB): 919kB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/zope.interface/setup.py) egg_info for package zope.interface

    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
Downloading/unpacking ua-parser (from user-agents->-r requirements.txt (line 13))
  Downloading ua-parser-0.3.6.tar.gz
  Running setup.py (path:/tmp/pip-build-yaWNFu/ua-parser/setup.py) egg_info for package ua-parser

Downloading/unpacking pyasn1-modules from https://pypi.python.org/packages/source/p/pyasn1-modules/pyasn1-modules-0.0.7.tar.gz#md5=9e92623a86709a77d43d406612ad7389 (from service-identity->-r requirements.txt (line 15))
  Downloading pyasn1-modules-0.0.7.tar.gz
  Running setup.py (path:/tmp/pip-build-yaWNFu/pyasn1-modules/setup.py) egg_info for package pyasn1-modules

Downloading/unpacking characteristic>=14.0.0 (from service-identity->-r requirements.txt (line 15))
  Downloading characteristic-14.3.0-py2.py3-none-any.whl
Downloading/unpacking Werkzeug>=0.7 from https://pypi.python.org/packages/2.7/W/Werkzeug/Werkzeug-0.10.4-py2.py3-none-any.whl#md5=4017a2ed262cfa973f76108eb488e5be (from Flask->-r requirements.txt (line 17))
  Downloading Werkzeug-0.10.4-py2.py3-none-any.whl (293kB): 293kB downloaded
Downloading/unpacking Jinja2>=2.4 from https://pypi.python.org/packages/2.7/J/Jinja2/Jinja2-2.8-py2.py3-none-any.whl#md5=75acb6f1abfc46ed75f4fd392f321ac2 (from Flask->-r requirements.txt (line 17))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Requirement already up-to-date: itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from Flask->-r requirements.txt (line 17))
Downloading/unpacking pycparser from https://pypi.python.org/packages/source/p/pycparser/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935 (from cffi>=1.1.0->cryptography->-r requirements.txt (line 5))
  Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
  Running setup.py (path:/tmp/pip-build-yaWNFu/pycparser/setup.py) egg_info for package pycparser

    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Requirement already up-to-date: MarkupSafe in /usr/lib/python2.7/dist-packages (from Jinja2>=2.4->Flask->-r requirements.txt (line 17))
Installing collected packages: cryptography, Pillow, netaddr, scapy, dnslib, Twisted, pefile, ipy, user-agents, service-identity, beautifulsoup4, capstone, python-magic, msgpack-python, pypcap, NetfilterQueue, argh, pathtools, watchdog, six, setuptools, enum34, cffi, zope.interface, ua-parser, pyasn1-modules, characteristic, Werkzeug, Jinja2, pycparser
  Found existing installation: cryptography 0.9.3
    Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for cryptography

    Installed /tmp/pip-build-yaWNFu/cryptography/cffi-1.1.2-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yaWNFu/cryptography/setup.py", line 307, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
    ImportError: No module named setuptools_ext
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-yaWNFu/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PXRGjH-record/install-record.txt --single-version-externally-managed --compile:


Installed /tmp/pip-build-yaWNFu/cryptography/cffi-1.1.2-py2.7-linux-x86_64.egg

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-yaWNFu/cryptography/setup.py", line 307, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options

    ep.load()(self, ep.name, value)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load

    ['__name__'])

ImportError: No module named setuptools_ext

----------------------------------------
  Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-yaWNFu/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PXRGjH-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-yaWNFu/cryptography
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by shimmy21** [comment]
Exactly the same problem

**Comment by byt3bl33d3r** [comment]
@vapor99 @shimmy21 there seems to be an issue with the new ```python-cryptography``` library update that just dropped, and kali 2.0.  As a temporary workaround:
- Make sure you have the old version installed by doing: ```apt-get install python-cryptography```
- Edit the ```requirements.txt``` file and remove the ```cryptography ``` entry
- Run: ```pip install -r requirements.txt```

**Comment by byt3bl33d3r** [comment]
@vapor99 @shimmy21 quick update, this seems to be resolved by installing the ```cffi``` library, see #163
