### ISSUE TITLE
Python installation error

### ISSUE THREAD

**Issue by DrDinosaur** [byt3bl33d3r/MITMf#161]
I'm using a Raspberry Pi 2 with Kali Linux 2.0.1. This is from "pip install --upgrade -r requirements.txt"

```
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-xGTw3D/pypcap
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-xGTw3D/pypcap
```

**Comment by BillKalaitzis** [comment]
Try manually installing pycap:
pip install PyCap

**Comment by byt3bl33d3r** [comment]
@DrDinosaur try using the new install instructions  https://github.com/byt3bl33d3r/MITMf/wiki/Installation

**Comment by DrDinosaur** [comment]
It's working now. Thanks.
