### ISSUE TITLE
I was getting this error.

### ISSUE THREAD

**Issue by thezakman** [byt3bl33d3r/MITMf#162]
Traceback (most recent call last):
  File "./mitmf.py", line 94, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/usr/share/mitmf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/usr/share/mitmf/core/sslstrip/ClientRequest.py", line 37, in <module>
    from ServerConnection import ServerConnection
  File "/usr/share/mitmf/core/sslstrip/ServerConnection.py", line 28, in <module>
    from user_agents import parse
ImportError: No module named user_agents

**Comment by thezakman** [comment]
Fixed with: pip install pyyaml ua-parser user-agents

**Comment by byt3bl33d3r** [comment]
@thezakman hey man, try using the new installation instructions https://github.com/byt3bl33d3r/MITMf/wiki/Installation it will make things easier :P

**Comment by mmc4future** [comment]
I am using kali linux i get some errors when I'm typing the commands in the instruction what should I do... and when i use python I get this error =>

|  |_ ARP spoofing enabled
Traceback (most recent call last):
  File "mitmf.py", line 138, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/root/MITMf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/root/MITMf/core/sslstrip/ClientRequest.py", line 37, in <module>
    from ServerConnection import ServerConnection
  File "/root/MITMf/core/sslstrip/ServerConnection.py", line 28, in <module>
    from user_agents import parse
ImportError: No module named user_agents

**Comment by mw3demo** [comment]
@mmc4future 

Did you install the dependencies via:

    pip install -r requirements.txt

If yes, first try: 

    pip install user_agents

Then try to launch MITMf again, if it still complains about no module named user_agents:

    pip install --upgrade --force-reinstall user_agents

Repeat for any missing modules, although pip install -r requirements.txt should have done it in the first place.

**Comment by mmc4future** [comment]
I did it thankssss

**Comment by mw3demo** [comment]
@mmc4future Great! Close this Github ticket if everything is up and running. :+1:
