### ISSUE TITLE
No traffic captured

### ISSUE THREAD

**Issue by micapoltron** [byt3bl33d3r/MITMf#182]
Hello,

I have problems getting any traffic using mitmf. Tried non-https sites. Check Wireshark, packages from target system are picked up. Installed from git. Added upsidedownternet just to easily see if it works. Sometimes it takes several tries to resolve MAC address, but after resolving, nothing happens. 

Setup:
```
Target router ip: 192.168.1.1, open connection
Target system ip: 192.168.1.2, connected by separate wifi adapter
Kali on VM, with TP-Link TL-WN722N adapter, connected to the router, ip 192.168.1.3
```

Command:
```
python mitmf.py -i wlan0 --spoof --arp --gateway 192.168.1.1 --target 192.168.1.2 --log-level debug --upsidedownternet
```

Output:
```
 v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
2015-09-02 02:10:01 [ProxyPlugins] Adding Spoof plugin
|_ Spoof v0.6
2015-09-02 02:10:01 [ARPpoisoner] gatewayip  => 192.168.1.1
2015-09-02 02:10:01 [ARPpoisoner] gatewaymac => e8:39:df:29:6c:08
2015-09-02 02:10:01 [ARPpoisoner] targets    => [IPAddress('192.168.1.2')]
2015-09-02 02:10:01 [ARPpoisoner] ignore     => []
2015-09-02 02:10:01 [ARPpoisoner] ip         => 192.168.1.3
2015-09-02 02:10:01 [ARPpoisoner] mac        => c4:e9:84:0d:57:e4
2015-09-02 02:10:01 [ARPpoisoner] interface  => wlan0
2015-09-02 02:10:01 [ARPpoisoner] arpmode    => rep
2015-09-02 02:10:01 [ARPpoisoner] interval   => 3
2015-09-02 02:10:01 [Utils] Setting ip forwarding to 1
|  |_ ARP spoofing enabled
2015-09-02 02:10:01 [ProxyPlugins] Adding Upsidedownternet plugin
|_ Upsidedownternet v0.1
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

2015-09-02 02:10:03 [ARPpoisoner] Resolved 192.168.1.2 => 6c:71:d9:f2:ee:6d
 ```

OS:
```
Attack OS: Kali 2.0
Victim OS: Windows 8.1; Firefox 40.0.3
```

pip freeze:
```
(MITMf)root@kali:~/MITMf# pip freeze
beautifulsoup4==4.4.0
capstone==3.0.4
cffi==1.2.1
characteristic==14.3.0
chardet==2.3.0
configobj==5.0.6
cryptography==1.0
dnslib==0.9.4
dnspython==1.12.0
enum34==1.0.4
Flask==0.10.1
idna==2.0
ipaddress==1.0.14
IPy==0.83
itsdangerous==0.24
Jinja2==2.8
lxml==3.4.4
MarkupSafe==0.23
msgpack-python==0.4.6
netaddr==0.7.17
NetfilterQueue==0.6
pefile==1.2.10.post114
Pillow==2.9.0
pyasn1==0.1.8
pyasn1-modules==0.0.7
pycparser==2.14
pycrypto==2.6.1
pyinotify==0.9.6
pyOpenSSL==0.15.1
pypcap==1.1.3
python-magic==0.4.6
requests==2.7.0
scapy==2.3.1
service-identity==14.0.0
six==1.9.0
Twisted==15.3.0
ua-parser==0.3.6
user-agents==0.3.2
Werkzeug==0.10.4
wheel==0.24.0
zope.interface==4.1.2
```

**Comment by HAMIDx9** [comment]
Hi,

As your scenario says it seems arp poisoner does not work correctly, you can verify this condition by using `arp -a` command on target and see if router mac is the same as kali mac address.

So Please check #178 issue (https://github.com/byt3bl33d3r/MITMf/issues/178) and its probable fix commit.

You can make the changes manually and revert back then.

Also repeat running MITMf multiple times to see if it happens frequently or not.

And if it is possible please verify your situation on seprated environment which target can be a phone or another pc.

@byt3bl33d3r, sorry for interrupting ;)

Thank you

**Comment by WiredLife** [comment]
Maybe the same problem? 
https://github.com/byt3bl33d3r/MITMf/issues/180

**Comment by byt3bl33d3r** [comment]
@micapoltron thanks for the well written report
yesterday I introduced a bug that was causing iptables to not set the rules for HTTP redirection, do a git pull and everything should be back to normal, If not comment below 

Thanks

**Comment by WiredLife** [comment]
thanks byt3bl33d3r!

**Comment by micapoltron** [comment]
@byt3bl33d3r Thanks for quick reply
Pulled the changes, and everything works.
Much obliged!

**Comment by M4nik** [comment]
What do you mean by git pull it didn't work for me

**Comment by subxero73** [comment]
port 9999 having same issue even if i change port under mitmf api i changed to 333 and this port nor 9999 is being used also fixed networking and interface problem this script is one of the best it would be nice to get a tutor i am just begginer but love coding and have alittle free time to do so anyways i definetly want to understand my issue more and seek to further my knowloledge love name btw good alias

**Comment by subxero73** [comment]
also running linux mint 18 xfce 64 bit using katoolin as install source for kali tools

**Comment by subxero73** [comment]
[*] MITMf v0.9.8 - 'The Dark Side'
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
Error starting HTTP server: [Errno 98] Address already in use
|_ HTTP server online
Exception in thread mitmfapi:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/mitmf/core/mitmfapi.py", line 90, in startFlask
    app.run(debug=False, host=self.host, port=self.port)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 708, in run_simple
    inner()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 670, in inner
    fd=fd)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 564, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 476, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

|_ DNSChef v0.4 online
Error starting SMB server: [Errno 98] Address already in use
|_ SMB server online

**Comment by subxero73** [comment]
any suggestions or advice would be nice thanks
