### ISSUE TITLE
Can't Run MITMF :( 

### ISSUE THREAD

**Issue by PentesterGuy** [byt3bl33d3r/MITMf#186]
Hello all, 

When i want to run the mitmf it give me this error I don't know why ? 
[*] MITMf v0.9.7 online... initializing plugins
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|_ Spoof v0.6
Traceback (most recent call last):
  File "./mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/usr/share/mitmf/plugins/Spoof.py", line 103, in initialize
    DNSChef.getInstance().loadRecords(self.dnscfg)
AttributeError: 'DNSChef' object has no attribute 'loadRecords'

The command which i run is this :
mitmf --hsts --arp --dns --spoof -i wlan0 --target [victim ip] --gateway [gateway ip]

Please anybody help me :) 

Best Regards,

**Comment by PentesterGuy** [comment]
Thanks Guys I solved the problem by Updating and using the the github files :) 

But wanted to ask that doesn't work all the time.
When i want to open any https website some times it doesn't work ? 
can anybody help me regarding that ? 

Best Regards 

PentesterGuy
