### ISSUE TITLE
Exception occurred in DHCP poisoner

### ISSUE THREAD

**Issue by xmcp** [byt3bl33d3r/MITMf#188]
- **OS**: Kali Linux 2
- **Interpreter**: CPython 2.7.9
- **MITMf Version**: Latest (commit `9add87c5b27efb7b5718c348a602454e0e3be5d6`)
- **Command String**: `mitmf.py --log-level debug -i eth0 --spoof --dhcp`

## Output
                                                        
     __  __   ___   .--.          __  __   ___              
    |  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
    |   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
    |  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
    |  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
    |  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
    |  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
    |__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                           |  '.'                   | |     
                           |   /                    | |     
                           `'-'                     |_|

    2015-09-06 18:33:08 MITMf started: ['/root/MITMf/mitmf.py', '--log-level', 'debug', '-i', 'eth0', '--spoof', '--dhcp']
    [*] MITMf v0.9.8 - 'The Dark Side'
    |
    |_ Net-Creds v1.0 online
    2015-09-06 18:33:08 [ProxyPlugins] Adding Spoof plugin
    |_ Spoof v0.6
    2015-09-06 18:33:08 [DHCPpoisoner] interface  => eth0
    2015-09-06 18:33:08 [DHCPpoisoner] ip         => 192.168.1.107
    2015-09-06 18:33:08 [DHCPpoisoner] mac        => 08:00:**:**:**:**
    2015-09-06 18:33:08 [DHCPpoisoner] netmask    => 255.255.255.0
    2015-09-06 18:33:08 [DHCPpoisoner] shellshock => None
    2015-09-06 18:33:08 [Utils] Setting ip forwarding to 1
    2015-09-06 18:33:08 [Utils] Setting iptables HTTP redirection rule from port 80 to 10000
    |  |_ DHCP spoofing enabled
    |_ Sergio-Proxy v0.2.1 online
    |_ SSLstrip v0.9 by Moxie Marlinspike online
    |
    |_ MITMf-API online
     * Running on http://127.0.0.1:9999/
    |_ HTTP server online
    |_ DNSChef v0.4 online
    |_ SMB server online

    2015-09-06 18:33:15 [DHCPpoisoner] Saw a DHCP packet
    2015-09-06 18:33:15 [DHCPpoisoner] Got DHCP DISCOVER from: 08:00:**:**:**:** xid: 0xea44****
    2015-09-06 18:33:15 [DHCPpoisoner] Sending DHCP OFFER
    2015-09-06 18:33:15 [DHCPpoisoner] Exception occurred while poisoning: must be string, not IPAddress

## Traceback
    Exception in thread DHCPpoisoner:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/root/MITMf/core/poisoners/DHCP.py", line 60, in dhcp_sniff
        sniff(filter="udp and (port 67 or 68)", prn=self.dhcp_callback, iface=self.interface)
      File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
        r = prn(p)
      File "/root/MITMf/core/poisoners/DHCP.py", line 116, in dhcp_callback
        self.s2.send(packet)
      File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 32, in send
        sx = str(x)
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 261, in __str__
        return self.build()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 319, in build
        p = self.do_build()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 311, in do_build
        pay = self.do_build_payload()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 303, in do_build_payload
        return self.payload.do_build()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 311, in do_build
        pay = self.do_build_payload()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 303, in do_build_payload
        return self.payload.do_build()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 311, in do_build
        pay = self.do_build_payload()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 303, in do_build_payload
        return self.payload.do_build()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 308, in do_build
        pkt = self.self_build()
      File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 299, in self_build
        p = f.addfield(self, p, val)
      File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 70, in addfield
        return s+struct.pack(self.fmt, self.i2m(pkt,val))
      File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 222, in i2m
        return inet_aton(x)
    TypeError: must be string, not IPAddress

## The `pip freeze` you want
    root@kali:~/MITMf# pip freeze
    Warning: cannot find svn location for apsw==3.8.6-r1
    BBQSQL==1.0
    BeautifulSoup==3.2.1
    BlindElephant==1.0
    Cheetah==2.4.4
    ConfigArgParse==0.9.3
    Elixir==0.7.1
    Flask==0.10.1
    GeoIP==1.3.2
    GitPython==0.3.2.RC1
    IPy==0.81
    Jinja2==2.7.3
    M2Crypto==0.21.1
    Magic-file-extensions==0.2
    Mako==1.0.0
    Markdown==2.5.1
    MarkupSafe==0.23
    MySQL-python==1.2.3
    NetfilterQueue==0.6
    NfSpy==1.0
    PAM==0.4.2
    Pillow==2.6.1
    PyBluez==0.18
    PyGithub==1.23.0
    PyOpenGL==3.0.2
    PySocks==1.5.0
    PyX==0.12.1
    PyYAML==3.11
    Pygments==2.0.1
    SOAPpy==0.12.22
    SQLAlchemy==0.9.8
    Twisted==14.0.2
    Twisted-Conch==14.0.2
    Twisted-Core==14.0.2
    Twisted-Lore==14.0.2
    Twisted-Mail==14.0.2
    Twisted-Names==14.0.2
    Twisted-News==14.0.2
    Twisted-Runner==14.0.2
    Twisted-Web==14.0.2
    Twisted-Words==14.0.2
    Werkzeug==0.9.6
    XlsxWriter==0.5.2
    Yapsy==1.10.423
    adns-python==1.2.1
    ## FIXME: could not find svn URL in dependency_links for this package:
    apsw==3.8.6-r1
    argcomplete==0.8.1
    argparse==1.2.1
    async==0.6.1
    beautifulsoup4==4.3.2
    binwalk==2.0.0
    blinker==1.3
    capstone==3.0
    certifi==2015.4.28
    cffi==0.8.6
    characteristic==0.1.0
    chardet==2.3.0
    chirp==0.4.0
    clamd==1.0.1
    cluster==1.1.1b3
    colorama==0.3.2
    configobj==5.0.6
    configparser==3.3.0r2
    cryptography==0.9.3
    ctypeslib==0.5.6
    d2to1==0.2.11
    darts.util.lru==0.5
    decorator==3.4.0
    defusedxml==0.4.1
    dicttoxml==1.6.6
    dissy==9
    distorm3==3
    dnslib==0.9.4
    dnspython==1.12.0
    docutils==0.12
    easygui==0.96
    ecdsa==0.11
    enum34==1.0.3
    esmre==0.3.1
    feedparser==5.1.3
    flickrapi==1.2
    funkload==1.16.1
    fuse-python==0.2.1
    futures==2.2.0
    gevent==1.0.1
    gitdb==0.5.4
    greenlet==0.4.2
    guess-language==0.2
    halberd==0.2.4
    hpack==1.1.0
    html2text==2015.6.21
    html5lib==0.999
    httplib2==0.9
    idna==2.0
    impacket==0.9.12
    ipaddress==1.0.14
    itsdangerous==0.24
    jsonpickle==0.8.0
    jsonrpclib==0.1.3
    keepnote==0.7.8
    killerbee==1.0
    lxml==3.4.0
    matplotlib==1.4.2
    mechanize==0.2.5
    mercurial==3.1.2
    metaconfig==0.1.4a1
    mitmproxy==0.13
    mock==1.0.1
    msgpack-python==0.4.4
    ndg-httpsclient==0.3.3
    netaddr==0.7.12
    netlib==0.13.1
    networkx==1.9
    nltk==3.0.0
    nose==1.3.4
    numpy==1.8.2
    oauth==1.0.1
    openpyxl==1.7.0
    paramiko==1.15.1
    passlib==1.6.1
    pcapy==0.10.8
    pdfminer==20140328
    pefile==1.2.9.1
    pexpect==3.2
    phply==0.9.1
    ply==3.4
    prettytable==0.7.2
    psutil==2.1.1
    psycopg2==2.5.4
    pyOpenSSL==0.15.1
    pyPdf==1.13
    pyasn1==0.1.7
    pyasn1-modules==0.0.5
    pybloomfiltermmap==0.3.14
    pycparser==2.10
    pycrypto==2.6.1
    pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
    pycups==1.9.63
    pycurl==7.19.5
    pydns==2.3.6
    pygobject==3.14.0
    pygraphviz==1.3rc2
    pyinotify==0.9.4
    pymssql==1.0.2
    pyparsing==2.0.3
    pypcap==1.1.3
    pyperclip==1.5.11
    pyqtgraph==0.0.0
    pyregfi==99.99.99.277
    pyrit==0.4.0
    pyrtlsdr==0.1.1
    pyscard==1.6.14
    pyserial==2.6
    pysmbc==1.0.15.3
    pysnmp==4.2.5
    pysnmp-apps==0.3.2
    pysnmp-mibs==0.1.3
    pysqlite==2.6.3
    python-Levenshtein==0.11.2
    python-apt==0.9.3.11
    python-dateutil==2.2
    python-debian==0.1.27
    python-debianbts==1.11
    python-magic==0.4.6
    python-ntlm==1.0.1
    pytidylib==0.2.1
    pytz==2012c
    pyusb==1.0.0a3
    pyxdg==0.25
    pyzmq==14.4.0
    reportbug==6.6.3
    requests==2.7.0
    rfidiot==1.0
    roman==2.0.0
    ruamel.ordereddict==0.4.8
    scapy==2.2.0
    scipy==0.14.0
    service-identity==1.0.0
    simplejson==3.6.5
    six==1.8.0
    slowaes==0.1a1
    smmap==0.8.2
    stopit==1.1.0
    tblib==0.2.0
    tornado==4.2
    tweepy==2.3
    uTidylib==0.2
    ua-parser==0.4.1
    urllib3==1.10.4
    urwid==1.3.0
    user-agents==1.0.1
    volatility==2.4
    vulndb==0.0.17
    wapiti==2.3.0
    webunit==1.3.10
    wheel==0.24.0
    wsgiref==0.1.2
    wstools==0.4.3
    wxPython==3.0.1.1
    wxPython-common==3.0.1.1
    xdot==0.5
    xsser==1.6
    yara-python==3.1
    zenmap==6.49BETA4
    zim==0.62
    zope.interface==4.1.1

**Comment by byt3bl33d3r** [comment]
@xmcp thanks for the awesome report, looking into this now

**Comment by byt3bl33d3r** [comment]
@xmcp pushed a fix, thanks again
