### ISSUE TITLE
MITMf kali 2 problem

### ISSUE THREAD

**Issue by 11moon11** [byt3bl33d3r/MITMf#213]
U just updated to Kali 2 and everything works just fine except mitmf: 

```
Traceback (most recent call last):
  File "./mitmf.py", line 32, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/FilePwn.py", line 68, in <module>
    from libs.bdfactory import pebin
  File "/usr/share/mitmf/libs/bdfactory/pebin.py", line 45, in <module>
    from intel.intelCore import intelCore
  File "/usr/share/mitmf/libs/bdfactory/intel/intelCore.py", line 38, in <module>
    from capstone import *
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 358, in <module>
    _setup_prototype(_cs, "cs_regs_access", ctypes.c_int, ctypes.c_size_t, ctypes.POINTER(_cs_insn), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8))
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 340, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libcapstone.so: undefined symbol: cs_regs_access
```

I tried removing and reinstalling it using apt-get - didn't help.

Then I successfully installed MITMf from github using 'mkvirtualenv' and it works just fine, but is there any way to fix MITMf provided by Kali Distro?

**Comment by byt3bl33d3r** [comment]
@11moon11 don't know why you would want to use the Kali version since it's outdated. You should file a bug report in Kali's bug tracker if your sure that this is a bug in the package
