### ISSUE TITLE
Python dep error in mitmf 0.9.8

### ISSUE THREAD

**Issue by ortholinux** [byt3bl33d3r/MITMf#219]
Hello, although the bugs are debugged in mitmf 0.9.8 and i guess the current situation is not a bug in the tool, but i've no idea how to get arround this problem, the problem as far as i think is due to python-magic dependency, the tool runs fine withought any errors with all plugins, but after a while of forwarding spoofed packets it gives an error like this:

[*] MITMf v0.9.8 - 'The Dark Side'
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ FilePwn v0.3
|  |_ BDFProxy v0.3.2 online
|  |_ Connected to Metasploit v4.11.5-2015103001
|_ JSKeylogger v0.2
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

2015-11-12 14:08:43 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 14:08:44 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/filepwn.py", line 644, in response
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'
2015-11-12 14:08:44 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 14:08:45 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/filepwn.py", line 644, in response
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'

and this is almost same error that i also get in bdfproxy latest version, i am using kali and updated all with its rolling repos and also the python-magic and the python magic is upto date as here:

root@kali:~# apt-get install python-magic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-magic is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1755 not upgraded.

so i dont know how to fix it, if i use the version 0.9.7 it gives the smb LOG error and if use the 0.9.8 it give above error and with this payload injection also dont work and i get no meterpreter or shell, i've also tried other payloads but none worked and even dont know the problem really is due to python-magic.
Help please.

**Comment by ortholinux** [comment]
Nevermind i've got it.

**Comment by ortholinux** [comment]
Well another problem with the tool guys although every plugin is working but its not patching, and instead saying patching failed as here:

root@windows:~# mitmf -i eth0 --spoof --arp --targets 192.168.1.7 --gateway 192.168.1.1 --filepwn

███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗  
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

[*] MITMf v0.9.8 - 'The Dark Side'
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ FilePwn v0.3
|  |_ BDFProxy v0.3.2 online
|  |_ Connected to Metasploit v4.11.5-2015103001
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

2015-11-12 20:21:40 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:41 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:41 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:42 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:42 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:45 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:45 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:46 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:46 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:46 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:47 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:48 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:51 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:51 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:52 192.168.1.7 [type:Firefox-3 os:Windows XP] www.example.com
2015-11-12 20:21:56 [FilePwn] Exception in binaryGrinder __init__() got an unexpected keyword argument 'XP_MODE'
2015-11-12 20:21:56 192.168.1.7 [type:Firefox-3 os:Windows XP] [FilePwn] Patching failed
