### ISSUE TITLE
No module named ua_parser

### ISSUE THREAD

**Issue by shufan123** [byt3bl33d3r/MITMf#225]
I am on kali 2.0
I have followed your steps exactly but i got into some compilation errors cause some dev packages which you didn't mention were missing so i installed them and reinstalled and everything was fine but whenever i try to hsts or inject i am greeted with this

 File "mitmf.py", line 138, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/root/MITMf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/root/MITMf/core/sslstrip/ClientRequest.py", line 37, in <module>
    from ServerConnection import ServerConnection
  File "/root/MITMf/core/sslstrip/ServerConnection.py", line 28, in <module>
    from user_agents import parse
  File "/usr/local/lib/python2.7/dist-packages/user_agents/__init__.py", line 3, in <module>
    from .parsers import parse
  File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 4, in <module>
    from ua_parser import user_agent_parser
ImportError: No module named ua_parser

BTW i tried `workon MITMf` now and i got this 

Traceback (most recent call last):
  File "mitmf.py", line 29, in <module>
    import core.responder.settings as settings
  File "/root/MITMf/core/responder/settings.py", line 24, in <module>
    from core.configwatcher import ConfigWatcher
  File "/root/MITMf/core/configwatcher.py", line 22, in <module>
    from configobj import ConfigObj
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/configobj.py", line 22, in <module>
    import six
ImportError: No module named six

Thanks

**Comment by shufan123** [comment]
i download the ua_parser lib :-) ....obviously but now i have another error

**Comment by byt3bl33d3r** [comment]
@shufan123 as the error message says you're missing the ```six``` module, which IIRC comes by default with python 2.7, you're either running an older version of python or you broke your python install

**Comment by shufan123** [comment]
@byt3bl33d3r actually you are right, i reinstalled after installing the dev packages you didn't mention and all went smooth but unfortunately i can't remember the packages 's names
