### ISSUE TITLE
c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory

### ISSUE THREAD

**Issue by riramar** [byt3bl33d3r/MITMf#229]
I'd include "apt-get install libffi-dev" as a requirement for arm versions since the file ffi.h is missing during "pip install -r requirements.txt".
```
Building wheels for collected packages: pyinotify, pycrypto, cryptography, Pillow, scapy, dnslib, Twisted, lxml, pefile, ipy, configobj, Flask, dnspython, capstone, python-magic, msgpack-python, pypcap, chardet, enum34, cffi, zope.interface, itsdangerous, pycparser, MarkupSafe
  Running setup.py bdist_wheel for pyinotify
  Stored in directory: /root/.cache/pip/wheels/25/23/a6/1cf2ff553c862d58295c55ab90bfe70a7b81ec50612e5e5270
  Running setup.py bdist_wheel for pycrypto
  Stored in directory: /root/.cache/pip/wheels/96/b0/e6/03e439d41cb2592b5c4c9c77873761d6cbd417b332076680cd
  Running setup.py bdist_wheel for cryptography
  Complete output from command /root/.virtualenvs/MITMf/bin/python2.7 -c "import setuptools;__file__='/tmp/pip-build-eNTNA3/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmphBdZSZpip-wheel-:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-eNTNA3/cryptography/setup.py", line 318, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
      return self.obtain(req, installer)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
      return installer(requirement)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1058, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
  Failed building wheel for cryptography
```

**Comment by byt3bl33d3r** [comment]
@riramar you got it ! thanks!

**Comment by NeverWait** [comment]
Works for me, thanks
