### ISSUE TITLE
I try'ed so hard install & run it under raspberian

### ISSUE THREAD

**Issue by Floppynator** [byt3bl33d3r/MITMf#243]
root@raspberrypi:~/MITMf# python mitmf.py --help
Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/MITMf/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
  File "/root/MITMf/libs/bdfactory/pebin.py", line 49, in <module>
    from intel.intelCore import intelCore
  File "/root/MITMf/libs/bdfactory/intel/intelCore.py", line 38, in <module>
    from capstone import *
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 286, in <module>
    ctypes.c_uint64, ctypes.c_size_t, ctypes.POINTER(ctypes.POINTER(_cs_insn)))
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 281, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libcapstone.so: undefined symbol: cs_disasm

i worked many hours on this to get it run but that exception appears when i try to start after install...

any idea?

**Comment by byt3bl33d3r** [comment]
First, obligatory youtube link https://www.youtube.com/watch?v=eVTXPUF4Oz4

Second, you're not following the installations instructions in the wiki [here](https://github.com/byt3bl33d3r/MITMf/wiki/Installation)

Third, raspberry won't be able to handle some of MITMf's plugins

**Comment by Floppynator** [comment]
Her!
Thanks for the answer. Here is another youtube Link http://youtu.be/EOnSh3QlpbQ

I made exactly the same you written in the instructions :(

The only thing that bot working was to install libcapstone3. Only libcapstone2 is aviable instead. 

Chears Chris

**Comment by Floppynator** [comment]
Damn German Handy autocorrect :)

**Comment by Floppynator** [comment]
Oh i have reinstall Capstone bist that donst work :(
