### ISSUE TITLE
MITMf is not starting at 4.0.0-kali1-amd64

### ISSUE THREAD

**Issue by tdp157** [byt3bl33d3r/MITMf#275]
root@kali:~/MITMf# python mitmf.py -i eth0

@@@@@@@@@@   @@@  @@@@@@@  @@@@@@@@@@   @@@@@@@@  
@@@@@@@@@@@  @@@  @@@@@@@  @@@@@@@@@@@  @@@@@@@@  
@@! @@! @@!  @@!    @@!    @@! @@! @@!  @@!       
!@! !@! !@!  !@!    !@!    !@! !@! !@!  !@!       
@!! !!@ @!@  !!@    @!!    @!! !!@ @!@  @!!!:!    
!@!   ! !@!  !!!    !!!    !@!   ! !@!  !!!!!:    
!!:     !!:  !!:    !!:    !!:     !!:  !!:       
:!:     :!:  :!:    :!:    :!:     :!:  :!:       
:::     ::    ::     ::    :::     ::    ::       
 :      :    :       :      :      :     :        

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
Traceback (most recent call last):
  File "mitmf.py", line 138, in <module>
    from core.sslstrip.StrippingProxy import StrippingProxy
  File "/root/MITMf/core/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/root/MITMf/core/sslstrip/ClientRequest.py", line 37, in <module>
    from ServerConnection import ServerConnection
  File "/root/MITMf/core/sslstrip/ServerConnection.py", line 28, in <module>
    from user_agents import parse
  File "/usr/local/lib/python2.7/dist-packages/user_agents/__init__.py", line 3, in <module>
    from .parsers import parse
  File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 4, in <module>
    from ua_parser import user_agent_parser
ImportError: No module named ua_parser

**Comment by byt3bl33d3r** [comment]
@tdp157 as the error says install the ua_parser module
