### ISSUE TITLE
Error install MITMF

### ISSUE THREAD

**Issue by tdp157** [byt3bl33d3r/MITMf#276]
root@kali:/usr/local/bin# mkvirtualenv MITMf -p /usr/bin/python2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /root/.virtualenvs/MITMf/bin/python2.7
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2304, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 40] Too many levels of symbolic links: '/root/.virtualenvs/MITMf/bin/python2.7'
root@kali:/usr/local/bin# mkvirtualenv --version
14.0.6

**Comment by byt3bl33d3r** [comment]
@tdp157 not exactly sure whats happening here, but you probably broke your kali install

**Comment by thiago325** [comment]
how can i solve this problem:

mkvirtualenv MITMf -p /usr/bin/python2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /root/.virtualenvs/MITMf/bin/python2.7
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1231, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 40] Too many levels of symbolic links: '/root/.virtualenvs/MITMf/bin/python2.7'

**Comment by thiago325** [comment]
Ok,i fixed this problem,its easy
you will remove first with this command:
step 1
rmvirtualenv MITMf 

the next step is to follow with the tutorial

mkvirtualenv MITMf -p /usr/bin/python2.7

i did in this way 

root@ACA80170:~# mkvirtualenv MITMf -p /usr/bin/python2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /root/.virtualenvs/MITMf/bin/python2.7
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1231, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 40] Too many levels of symbolic links: '/root/.virtualenvs/MITMf/bin/python2.7'
root@ACA80170:~# rmvirtualenv MITMf
Removing MITMf...
root@ACA80170:~# mkvirtualenv MITMf -p /usr/bin/python2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /root/.virtualenvs/MITMf/bin/python2.7
Also creating executable in /root/.virtualenvs/MITMf/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /root/.virtualenvs/MITMf/bin/predeactivate
virtualenvwrapper.user_scripts creating /root/.virtualenvs/MITMf/bin/postdeactivate
virtualenvwrapper.user_scripts creating /root/.virtualenvs/MITMf/bin/preactivate
virtualenvwrapper.user_scripts creating /root/.virtualenvs/MITMf/bin/postactivate
virtualenvwrapper.user_scripts creating /root/.virtualenvs/MITMf/bin/get_env_details
(MITMf) root@ACA80170:~# ^C
(MITMf) root@ACA80170:~#
