### ISSUE TITLE
Unable to launch dhcp module -  no attribute ip address

### ISSUE THREAD

**Issue by thezjir** [byt3bl33d3r/MITMf#285]
' sudo mitmf --interface eth0 --spoof --dhcp --shellshock "echo 'rekt'" 

```
   ▄▄▄▄███▄▄▄▄    ▄█      ███       ▄▄▄▄███▄▄▄▄      ▄████████ 
 ▄██▀▀▀███▀▀▀██▄ ███  ▀█████████▄ ▄██▀▀▀███▀▀▀██▄   ███    ███ 
 ███   ███   ███ ███▌    ▀███▀▀██ ███   ███   ███   ███    █▀  
 ███   ███   ███ ███▌     ███   ▀ ███   ███   ███  ▄███▄▄▄     
 ███   ███   ███ ███▌     ███     ███   ███   ███ ▀▀███▀▀▀     
 ███   ███   ███ ███      ███     ███   ███   ███   ███        
 ███   ███   ███ ███      ███     ███   ███   ███   ███        
  ▀█   ███   █▀  █▀      ▄████▀    ▀█   ███   █▀    ███        

[*] MITMf v0.9.7 online... initializing plugins
|_ Spoof v0.6
Traceback (most recent call last):
  File "./mitmf.py", line 136, in <module>
    p.initialize(args)
  File "/usr/share/mitmf/plugins/Spoof.py", line 92, in initialize
    dhcp = DHCPServer(options.interface, self.dhcpcfg, options.ip_address, options.mac_address)
AttributeError: 'Namespace' object has no attribute 'ip_address'  '

```

**Comment by byt3bl33d3r** [comment]
You're using an old version of MITMf. Install the latest version and you'll be good to go.
