### ISSUE TITLE
mitmf not run 

### ISSUE THREAD

**Issue by vannisca** [byt3bl33d3r/MITMf#302]
hi guys , when i try .** /mitmf.py -i wlan0 --spoof --arp --hsts --gateway 192.168.1.1 --target 192.168.1.4  --jskeylogger **  show this output

screenshot
`http://i65.tinypic.com/2i7po5i.png`

016-04-10 11:07:11 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:11 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:12 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:12 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:12 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:12 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:13 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:13 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:13 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:13 192.168.1.9 [type:Chrome-49 os:Windows 7] ajax.googleapis.com
2016-04-10 11:07:13 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:14 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:14 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:14 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:14 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:14 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:15 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:15 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:15 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:15 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:15 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:15 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:15 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:15 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:16 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:16 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:16 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:16 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:17 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:17 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:17 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:17 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:17 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:18 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-04-10 11:07:18 192.168.1.9 [type:Chrome-49 os:Windows 7] punto-informatico.it
2016-04-10 11:07:18 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/inject.py", line 59, in response
    mime = response.headers['Content-Type']
2016-04-10 11:10:06 192.168.1.9 [DNS] Could not proxy request: timed out

****
I have the last version of kali linux and the last version of mitmf that i installed throught ./setup-fixed.sh

why i have this errors ??

**Comment by Britskiy** [comment]
`sudo python mitmf.py ....`

**Comment by byt3bl33d3r** [comment]
Resolved in 2dc1dd4f1260c34d168d25c0b387980ca3a2b247
