### ISSUE TITLE
'Upsidedonwternet' Plugin error. (Error Reported according to Guidelines)

### ISSUE THREAD

**Issue by prairie-guy** [byt3bl33d3r/MITMf#308]
I am running the kali-rolling distribution of NetHunter Kali on the Nexus 6P (angler-03.61). I had previously been running the kali-sana distribution. With the change of distributions, MITMf was upgraded from 0.9.7 to 0.9.8. In 0.9.7, 'Upsidedownternet' worked as expected, but in 0.9.8, it returns the error highlighted below. (I am not sure if this is a problem with the apt-get package or with 0.9.8. I will post to the Kali Repo as well.)

From debugging output, not clear that error even makes it to executing the 'upsidedownternet' plugin. As to other plugins, I am able to report success with the plugins: 'hsts' and 'spoof' (arp and dns). I am able to do some limited ssl+ stripping.

Here is the output of 'pip freeze'

```
argcomplete==1.0.0
argh==0.26.1
attrs==15.2.0
backports.ssl-match-hostname==3.4.0.2
BeautifulSoup==3.2.1
beautifulsoup4==4.4.1
blinker==1.3
capstone==3.0.4
certifi==2015.11.20.1
chardet==2.3.0
click==6.6
colorama==0.3.7
ConfigArgParse==0.10.0
configobj==5.0.6
construct==2.5.2
cryptography==1.3.1
dicttoxml==1.6.6
dnslib==0.9.4
dnspython==1.12.0
enum34==1.1.2
feedparser==5.1.3
Flask==0.10.1
future==0.15.2
gps==3.15
h2==2.1.1
hpack==2.1.0
html2text==2016.4.2
html5lib==0.999
hyperframe==3.2.0
idna==2.1
impacket==0.9.13
ipaddress==1.0.16
IPy==0.83
itsdangerous==0.24
Jinja2==2.8
jsonrpclib==0.1.3
lxml==3.6.0
M2Crypto==0.24.0
Magic-file-extensions==0.2
Mako==1.0.4
MarkupSafe==0.23
mechanize==0.2.5
mitmproxy==0.17.1
msgpack-python==0.4.6
mysqlclient==1.3.7
ndg-httpsclient==0.4.0
netaddr==0.7.18
NetfilterQueue==0.6
netifaces==0.10.4
numpy==1.11.0
olefile==0.42.1
PAM==0.4.2
passlib==1.6.5
pathtools==0.1.2
pcapy==0.10.8
pefile==2016.3.28
Pillow==3.2.0
pyasn1==0.1.9
pyasn1-modules==0.0.7
PyAudio==0.2.8
pycrypto==2.6.1
pycurl==7.43.0
pyinotify==0.9.5
pyOpenSSL==16.0.0
pyparsing==2.0.3
PyPDF2==1.25.1
pyperclip==1.5.11
pyrit==0.4.0
pyserial==3.0.1
PyYAML==3.11
requests==2.9.1
scapy==2.2.0
service-identity==16.0.0
shodan==1.0.2
simplejson==3.8.2
six==1.10.0
slowaes==0.1a1
SQLAlchemy==1.0.12
tornado==4.2.1
Twisted==16.1.1
twitter==1.15.0
ua-parser==0.3.6
urllib3==1.13.1
urwid==1.3.1
user-agents==0.3.2
uTidylib==0.2
watchdog==0.8.3
Werkzeug==0.10.4
XlsxWriter==0.7.3
zope.interface==4.1.3
```

The full output of MITMf in debug mode and the full error traceback:

```
2016-04-28 21:52:41 MITMf started: ['./mitmf.py', '--log', 'debug', '-i', 'wlan0', '--upsidedownternet', '--spoof', '--arp', '--gateway', '10.10.10.1', '--target', '10.10.10.243']
[*] MITMf v0.9.8 - 'The Dark Side'
2016-04-28 21:52:42 [ProxyPlugins] Adding Spoof plugin
|_ Spoof v0.6
2016-04-28 21:52:42 [ARPpoisoner] gatewayip  => 10.10.10.1
2016-04-28 21:52:42 [ARPpoisoner] gatewaymac => 88:15:44:69:1e:90
2016-04-28 21:52:42 [ARPpoisoner] targets    => [IPAddress('10.10.10.243')]
2016-04-28 21:52:42 [ARPpoisoner] ignore     => []
2016-04-28 21:52:42 [ARPpoisoner] ip         => 10.10.10.139
2016-04-28 21:52:42 [ARPpoisoner] mac        => 94:fe:22:01:bf:e2
2016-04-28 21:52:42 [ARPpoisoner] interface  => wlan0
2016-04-28 21:52:42 [ARPpoisoner] arpmode    => rep
2016-04-28 21:52:42 [ARPpoisoner] interval   => 3
2016-04-28 21:52:42 [Utils] Setting ip forwarding to 1
2016-04-28 21:52:42 [Utils] Setting iptables HTTP redirection rule from port 80 to 10000
|  |_ ARP spoofing enabled
2016-04-28 21:52:42 [ProxyPlugins] Adding Upsidedownternet plugin
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ Upsidedownternet v0.1
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

2016-04-28 21:52:44 [ARPpoisoner] Unable to resolve MAC address of 10.10.10.243
2016-04-28 21:52:47 [ARPpoisoner] Resolved 10.10.10.243 => 70:48:0f:97:58:45
2016-04-28 21:52:51 [ClientRequest] Resolving host: theoreticalminimum.com
2016-04-28 21:52:51 [ClientRequest] Host not cached.
2016-04-28 21:52:51 [ClientRequest] Resolving with DNSChef
2016-04-28 21:52:51 127.0.0.1 [DNS] Proxying the response of type 'A' for theoreticalminimum.com
2016-04-28 21:52:51 [ClientRequest] Resolved host successfully: theoreticalminimum.com -> 50.56.49.247
2016-04-28 21:52:51 [ClientRequest] Zapped encoding
2016-04-28 21:52:51 [ClientRequest] Sending request via HTTP
2016-04-28 21:52:52 [ServerConnection] HTTP connection made.
2016-04-28 21:52:52 [ProxyPlugins] hooking connectionMade()
2016-04-28 21:52:52 10.10.10.243 [type:Mobile Safari-9 os:iOS] theoreticalminimum.com
2016-04-28 21:52:52 [ServerConnection] Full request: theoreticalminimum.com/
2016-04-28 21:52:52 [ServerConnection] Sending header: (accept-language: en-us)
2016-04-28 21:52:52 [ServerConnection] Sending header: (host: theoreticalminimum.com)
2016-04-28 21:52:52 [ServerConnection] Sending header: (accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8)
2016-04-28 21:52:52 [ServerConnection] Sending header: (user-agent: Mozilla/5.0 (iPad; CPU OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 Safari/601.1)
2016-04-28 21:52:52 [ServerConnection] Sending header: (connection: keep-alive)
2016-04-28 21:52:52 [ServerConnection] Sending header: (cookie: __utma=99109979.944274327.1377867624.1461877335.1461879963.13; __utmb=99109979.2.10.1461879963; __utmc=99109979; __utmt=1; __utmz=99109979.1455001170.11.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); adaptive_image=1366; has_js=1)
2016-04-28 21:52:52 [ServerConnection] Sending header: (pragma: no-cache)
2016-04-28 21:52:52 [ServerConnection] Sending header: (cache-control: max-age=0)
2016-04-28 21:52:52 [ProxyPlugins] hooking handleStatus()
2016-04-28 21:52:52 [ServerConnection] Server response: HTTP/1.1 200 OK
2016-04-28 21:52:52 [ProxyPlugins] hooking handleEndHeaders()
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 462, in lineReceived
    sFile Edit Options Buffers Tools Help                                                                                                                                                         
  File "/usr/share/mitmf/core/sslstrip/ServerConnection.py", line 182, in handleEndHeaders
    for header, value in self.client.headers.iteritems():
exceptions.AttributeError: ClientRequest instance has no attribute 'headers'

2016-04-28 21:52:52 [ProxyPlugins] hooking handleResponse()
2016-04-28 21:52:52 [ServerConnection] Read from server 0 bytes of data


2016-04-28 21:53:01 [ARPpoisoner] Restoring connection 10.10.10.243 <-> 10.10.10.1 with 2 packets per host
2016-04-28 21:53:01 [Utils] Flushing iptables
2016-04-28 21:53:01 [Utils] Setting ip forwarding to 0

```

Thanks in advance.

**Comment by jakuta-tech** [comment]
Try uninstalling Twisted 16 and install Twisted 15 instead

`pip uninstall Twisted`

then

`pip install Twisted==15.5.0`

**Comment by prairie-guy** [comment]
This is clearly a lack of my understanding of how pip works with virtualenv. . . 
Her is the result of running 
pip uninstall Twisted
```
Not uninstalling twisted at /usr/lib/python2.7/dist-packages, outside environment /usr
```
I of course am googling this on my own, but if I anyone knows how to do this within NetHunter Kali Linux, I would appreciate the help.

**Comment by prairie-guy** [comment]
'upsidedonwternet' is working!

```pip uninstall Twisted``` does not work. 
```pip freeze``` indicates Twisted==16.1.1 installed at ```/usr/lib/python2.7/dist-packages/```

```pip install Twisted==15.5.0``` does work.
```pip freeze``` indicates that Twisted==15.5.0 is installed at  ```/usr/local/lib/python2.7/dist-packages/```

So, installing Twisted==15.5.0 essentially masks Twisted==16.1.1

Solves this problem, not sure it breaks something else . . .

For now problem solved. Thanks jakuta-tech for your help.

**Comment by jakuta-tech** [comment]
@prairie-guy glad it worked.

I compile mitmf outside virtualenv on Nethunter and it works fine.  In your example above, it can see the library installed in your system Python environment as satisfying the dependency, so that's why it works.  If you're doing venv then you would want to be inside your virtualenv to do the pip installs.

As a test, in virtualenv I install latest Twisted 16 that doesn't work with mitmf.

```
(env1) root@kali:/tmp# pip install Twisted
Collecting Twisted
  Downloading Twisted-16.1.1.tar.bz2 (2.9MB)
    100% |████████████████████████████████| 2.9MB 115kB/s 
Collecting zope.interface>=3.6.0 (from Twisted)
  Downloading zope.interface-4.1.3.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 550kB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in /root/.virtualenvs/env1/lib/python2.7/site-packages (from zope.interface>=3.6.0->Twisted)
Building wheels for collected packages: Twisted, zope.interface
  Running setup.py bdist_wheel for Twisted ... done
  Stored in directory: /root/.cache/pip/wheels/bc/52/68/587c03fee7d98f2e61b8f410e0a31270d0b35e799d839fc650
  Running setup.py bdist_wheel for zope.interface ... done
  Stored in directory: /root/.cache/pip/wheels/52/04/ad/12c971c57ca6ee5e6d77019c7a1b93105b1460d8c2db6e4ef1
Successfully built Twisted zope.interface
Installing collected packages: zope.interface, Twisted
Successfully installed Twisted-16.1.1 zope.interface-4.1.3

(env1) root@kali:/tmp# pip freeze
Twisted==16.1.1
zope.interface==4.1.3
```

Then remove Twisted 16 

```
(env1) root@kali:/tmp# pip uninstall Twisted
Uninstalling Twisted-16.1.1:
  /root/.virtualenvs/env1/bin/cftp
  /root/.virtualenvs/env1/bin/ckeygen
<snip>
Proceed (y/n)? y
  Successfully uninstalled Twisted-16.1.1
```
and install Twisted 15 still inside virtualenv, which does work with mitmf
```
(env1) root@kali:/tmp# pip install Twisted==15.5.0
Collecting Twisted==15.5.0
  Downloading Twisted-15.5.0.tar.bz2 (3.1MB)
    100% |████████████████████████████████| 3.2MB 105kB/s 
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=3.6.0 in /root/.virtualenvs/env1/lib/python2.7/site-packages (from Twisted==15.5.0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /root/.virtualenvs/env1/lib/python2.7/site-packages (from zope.interface>=3.6.0->Twisted==15.5.0)
Building wheels for collected packages: Twisted
  Running setup.py bdist_wheel for Twisted ... done
  Stored in directory: /root/.cache/pip/wheels/d0/64/67/280d57eda5a61337fad955994a4bfe66b23c58e598469077b4
Successfully built Twisted
Installing collected packages: Twisted
Successfully installed Twisted-15.5.0

```

You can see python virtualenv and system locations.
```

(env1) root@kali:/tmp# python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
/root/.virtualenvs/env1/lib/python2.7/site-packages
(env1) root@kali:/tmp# deactivate
root@kali:/tmp# python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
/usr/lib/python2.7/dist-packages

```

so you may have changed Twisted in your system but it shouldn't cause too many problems

**Comment by prairie-guy** [comment]
Thanks! Based on the MITMf build instructions, I had assumed that a virtualenv existed within the Kali package. (I wasn't able to find it. Now I know I didn't miss it.) Helpful to see how you actually did it with virtualenv. I'll see how 15.5 exists in the System environment. 

If you have had to make any other "tweaks" to MITMf, would you let me know. 

Thanks again.
