### ISSUE TITLE
Error in smbtrap plugin

### ISSUE THREAD

**Issue by issacten** [byt3bl33d3r/MITMf#309]
I am seeing this error when including smbtrap plugin in mitmf command:

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 853, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 468, in format
    s = self._fmt % record.__dict__
KeyError: 'clientip'
Logged from file smbtrap.py, line 36
````

I looked into smbtrap.py, it seems back-port was missed for module update - similar issue to #146
Please fix this.

````python
self.clientlog.info("Trapping request to {}".format(request.headers['host']))
````

**Comment by byt3bl33d3r** [comment]
Resolved in 2dc1dd4f1260c34d168d25c0b387980ca3a2b247
