### ISSUE TITLE
Filepwn error

### ISSUE THREAD

**Issue by FreelancePentester** [byt3bl33d3r/MITMf#319]
File "/root/MITMf/plugins/filepwn.py", line 644, in response
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'
2016-06-19 19:41:59 192.168.1.7 [type:Chrome Mobile-38 os:Android] www.google.com
2016-06-19 19:41:59 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 116, in hook
    a = f(**args)
  File "/root/MITMf/plugins/filepwn.py", line 644, in response
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'
2016-06-19 19:41:59 192.168.1.7 [type:Chrome Mobile-38 os:Android] www.google.com.vn
2016-06-19 19:41:59 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 116, in hook
    a = f(**args)
  File "/root/MITMf/plugins/filepwn.py", line 644, in response
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'
2016-06-19 19:42:07 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 116, in hook
    a = f(**args)
  File "/root/MITMf/plugins/filepwn.py", line 644, in response
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'
2016-06-19 19:42:10 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 116, in hook
    a = f(**args)
  File "/root/MITMf/plugins/filepwn.py", line 644, in response
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'
2016-06-19 19:42:15 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/proxyplugins.py", line 116, in hook
    a = f(**args)
  File "/root/MITMf/plugins/filepwn.py", line 644, in response
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'

**Comment by FreelancePentester** [comment]
[*] In the backdoor module
[*] Checking if binary is supported
[*] Gathering file info
[*] Reading win32 entry instructions
[*] Loading PE in pefile
[*] Parsing data directories
[*] Adding New Section for updated Import Table
[!] File has extra data after last section, cannot add new section
2016-06-21 21:43:22 192.168.1.66 [type:Firefox-48 os:Windows 7] [FilePwn] Patching failed

**Comment by cpt-n3mo** [comment]
@FreelancePentester 
could you please tel me how you fixed these errors,, i have the exact same problem, running arch linux 
Kr

**Comment by FreelancePentester** [comment]
change SHELL on mitmf config file

**Comment by cpt-n3mo** [comment]
hello and thank for you responce, I changed the "SHELL =" to many different shell types as u described, but non seem to work, could you maybe be a bit more detailed about what u changed your SHELL into. 
Kr

**Comment by Cosmic4x2** [comment]
hello I am having a problem with the filepwn as well I download putty.exe  it shows [FilePwn] Patching complete, forwarding to user although when I execute putty I get  "putty.exe is not a valid Win32 application" can you please tell me how to fix this. I am running putty on a Win 7 machine.

Thx

**Comment by FreelancePentester** [comment]
how to resolve this error, please visite here: http://kali-linux.co/forums/topic/backdoor-on-the-fly-with-bdfproxy/

**Comment by Cosmic4x2** [comment]
ok.. I seem to be getting closer now when i download putty.exe in msfconsle
I get Sending stage (957999 bytes) to 192.168.1.124 but does not open the
session.

Thx

**Comment by byt3bl33d3r** [comment]
From the traceback it looks like theres a problem with the magic library. @FreelancePentester:
1)  did you follow the install instructions?
2) what version are you using?
3) full debug output would be nice.
Thanks
