### ISSUE TITLE
config.obj Duplicate Error

### ISSUE THREAD

**Issue by noczero** [byt3bl33d3r/MITMf#323]
I got this some error after installing. and run some script

Traceback (most recent call last):
  File "./mitmf.py", line 81, in <module>
    settings.Config.populate(options)
  File "/usr/share/mitmf/core/responder/settings.py", line 72, in populate
    self.SSL_On_Off      = self.toBool(self.config['Responder']['HTTPS'])
  File "/usr/share/mitmf/core/configwatcher.py", line 28, in config
    return ConfigObj("./config/mitmf.conf")
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1318, in _load
    raise error
configobj.DuplicateError: Duplicate keyword name at line 38.

**Comment by byt3bl33d3r** [comment]
Did you mess with the config file? Try doing ```git reset --hard```
