### ISSUE TITLE
CAN NOT IMPORT LOG.py

### ISSUE THREAD

**Issue by JackPurPle** [byt3bl33d3r/MITMf#327]
While I start mitmf ,the error shows like this:

[*] MITMf v0.9.7 online... initializing plugins
|_ Inject v0.3
|_ Spoof v0.6
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
Traceback (most recent call last):
  File "./mitmf.py", line 180, in <module>
    from core.protocols.smb.SMBserver import SMBserver
  File "/usr/share/mitmf/core/protocols/smb/SMBserver.py", line 5, in <module>
    from impacket import version, smbserver, LOG
ImportError: cannot import name LOG

Look ,I can not import LOG,but I can import version,smbserver
I searched my directories ,found directory of impacket 
version.py and smbserver.py do exist but 
WHY
I can not find LOG.py anywhere  T_T
I reinstall impacket several times but can't find LOG.py either

Question:
1.Does LOG.py automatically generated by system or by some instructions?
2.IF you have LOG.py in directory of impacket ,could you please send me one? SOS! T-T
MY MAIL ADRESS :doubihj@mail.ustc.edu.cn

thank you so much for your patience!

**Comment by JackPurPle** [comment]
okay I've fixed my problem by rewritting __init__.py,seems it's runs smoothly in the first few steps
rewrite it like this:
# Copyright (c) 2003-2015 CORE Security Technologies)
#
# This software is provided under under a slightly modified version
# of the Apache Software License. See the accompanying LICENSE file
# for more information.
#
# Author: Alberto Solino (@agsolino)
#

# Set default logging handler to avoid "No handler found" warnings.
import logging
try:  # Python 2.7+
    from logging import NullHandler
except ImportError:
    class NullHandler(logging.Handler):
        def emit(self, record):
            pass

# All modules inside this library MUST use this logger (impacket)
# It is up to the library consumer to do whatever is wanted 
# with the logger output. By default it is forwarded to the 
# upstream logger

LOG = logging.getLogger(__name__)
LOG.addHandler(NullHandler())


WELL,HERE COMES A NEW PROMBLEM   T-T


[*] MITMf v0.9.7 online... initializing plugins
|_ Inject v0.3
|_ Spoof v0.6
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
|_ SMBserver online (Impacket 9.10)

Traceback (most recent call last):
  File "./mitmf.py", line 182, in <module>
    SMBserver().start()
  File "/usr/share/mitmf/core/protocols/smb/SMBserver.py", line 29, in __init__
    self.server = smbserver.SimpleSMBServer(listenAddress, listenPort, configFile)
AttributeError: 'module' object has no attribute 'SimpleSMBServer'

I got no idea which file to edit this time

**Comment by JackPurPle** [comment]
......why  it turns to be so huge

**Comment by JackPurPle** [comment]
fine I got it,I downlaod the newest version of compacket and solve everything - -
