### ISSUE TITLE
Exception in thread mitmfapi

### ISSUE THREAD

**Issue by Romulocs** [byt3bl33d3r/MITMf#345]
**mitmf -i wlan0 --spoof --arp --dns --hsts -k --gateway 192.168.1.1 --target 192.168.1.102**

```
[*] MITMf v0.9.8 - 'The Dark Side'
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|_ Spoof v0.6
|  |_ DNS spoofing enabled
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

Exception in thread mitmfapi:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/mitmf/core/mitmfapi.py", line 90, in startFlask
    app.run(debug=False, host=self.host, port=self.port)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 550, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

^C
```

**Comment by Romulocs** [comment]
someone help me? :)

**Comment by HAMIDx9** [comment]
Hi
Apparently you have a software listening on port 9999. 
Stop that app or change mitmfapi port in mitm.conf and try again.

**Comment by jlxip** [comment]
To see if it's what HAMIDx9 said, try this out: `sudo netstat -tulpn | grep 9999` and you should see the process using it. Just kill it with `kill <PROCESS>`

**Comment by Romulocs** [comment]
Thank you guys, it was the "popcorntime" that was open. ^^'

**Comment by byt3bl33d3r** [comment]
If I had a penny for every time an issue was opened with this error I'd have probably around 100 pennies.
