### ISSUE TITLE
Could someone help me with kali linux

### ISSUE THREAD

**Issue by rainmansy** [byt3bl33d3r/MITMf#365]
when i type in "mitmf --arp --spoof  --target 192.168.12.1 --gateway 192.168.12.1 -i wlan0"
it doesn't work, i dont know what happened and how to fix
Traceback (most recent call last):
  File "./mitmf.py", line 77, in <module>
    from core.utils import get_ip, get_mac, shutdown
  File "/usr/share/mitmf/core/utils.py", line 26, in <module>
    from scapy.all import get_if_addr, get_if_hwaddr, get_working_if
  File "/usr/lib/python2.7/dist-packages/scapy/all.py", line 28, in <module>
    from scapy.route6 import *
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 273, in <module>
    conf.route6 = Route6()
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 31, in __init__
    self.resync()
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 44, in resync
    self.routes = read_routes6()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 283, in read_routes6
    cset = scapy.utils6.construct_source_candidate_set(d, dp, devaddrs, LOOPBACK_NAME)
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 50, in construct_source_candidate_set
    if in6_isgladdr(addr) or in6_isuladdr(addr):
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 708, in in6_isgladdr
    return in6_isincluded(str, '2000::', 3)
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 651, in in6_isincluded
    temp = inet_pton(socket.AF_INET6, addr)
  File "/usr/lib/python2.7/dist-packages/scapy/pton_ntop.py", line 40, in inet_pton
    raise Exception("Illegal syntax for IP address")
Exception: Illegal syntax for IP address

**Comment by Ritiek** [comment]
@rainmansy Why is it that target and gateway are same? Remove the target if you want to spoof all the devices connected to the gateway.

**Comment by rainmansy** [comment]
sorry I typed the wrong IP, but the result is still same.

**Comment by rainmansy** [comment]
root@kali:~# mitmf --arp --spoof  --target 192.168.15.35 --gateway 192.168.12.1 -i wlan0 

   ▄▄▄▄███▄▄▄▄    ▄█      ███       ▄▄▄▄███▄▄▄▄      ▄████████ 
 ▄██▀▀▀███▀▀▀██▄ ███  ▀█████████▄ ▄██▀▀▀███▀▀▀██▄   ███    ███ 
 ███   ███   ███ ███▌    ▀███▀▀██ ███   ███   ███   ███    █▀  
 ███   ███   ███ ███▌     ███   ▀ ███   ███   ███  ▄███▄▄▄     
 ███   ███   ███ ███▌     ███     ███   ███   ███ ▀▀███▀▀▀     
 ███   ███   ███ ███      ███     ███   ███   ███   ███        
 ███   ███   ███ ███      ███     ███   ███   ███   ███        
  ▀█   ███   █▀  █▀      ▄████▀    ▀█   ███   █▀    ███        

Traceback (most recent call last):
  File "./mitmf.py", line 77, in <module>
    from core.utils import get_ip, get_mac, shutdown
  File "/usr/share/mitmf/core/utils.py", line 26, in <module>
    from scapy.all import get_if_addr, get_if_hwaddr, get_working_if
  File "/usr/lib/python2.7/dist-packages/scapy/all.py", line 28, in <module>
    from scapy.route6 import *
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 273, in <module>
    conf.route6 = Route6()
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 31, in __init__
    self.resync()
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 44, in resync
    self.routes = read_routes6()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 283, in read_routes6
    cset = scapy.utils6.construct_source_candidate_set(d, dp, devaddrs, LOOPBACK_NAME)
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 50, in construct_source_candidate_set
    if in6_isgladdr(addr) or in6_isuladdr(addr):
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 708, in in6_isgladdr
    return in6_isincluded(str, '2000::', 3)
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 651, in in6_isincluded
    temp = inet_pton(socket.AF_INET6, addr)
  File "/usr/lib/python2.7/dist-packages/scapy/pton_ntop.py", line 40, in inet_pton
    raise Exception("Illegal syntax for IP address")
Exception: Illegal syntax for IP address

**Comment by Ritiek** [comment]
@rainmansy I don't know what is causing the problem but you might have luck by updating scapy.
Try `sudo pip install scapy --upgrade`

**Comment by rainmansy** [comment]
@Ritiek  still not work 

root@kali:~# mitmf --arp --spoof --target 192.168.15.49 --gateway 192.168.12.1 -i wlan0 
                                                    
 __  __   ___   .--.          __  __   ___              
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

Traceback (most recent call last):
  File "./mitmf.py", line 77, in <module>
    from core.utils import get_ip, get_mac, shutdown
  File "/usr/share/mitmf/core/utils.py", line 26, in <module>
    from scapy.all import get_if_addr, get_if_hwaddr, get_working_if
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 28, in <module>
    from scapy.route6 import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/route6.py", line 273, in <module>
    conf.route6 = Route6()
  File "/usr/local/lib/python2.7/dist-packages/scapy/route6.py", line 31, in __init__
    self.resync()
  File "/usr/local/lib/python2.7/dist-packages/scapy/route6.py", line 44, in resync
    self.routes = read_routes6()
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 283, in read_routes6
    cset = scapy.utils6.construct_source_candidate_set(d, dp, devaddrs, LOOPBACK_NAME)
  File "/usr/local/lib/python2.7/dist-packages/scapy/utils6.py", line 50, in construct_source_candidate_set
    if in6_isgladdr(addr) or in6_isuladdr(addr):
  File "/usr/local/lib/python2.7/dist-packages/scapy/utils6.py", line 708, in in6_isgladdr
    return in6_isincluded(str, '2000::', 3)
  File "/usr/local/lib/python2.7/dist-packages/scapy/utils6.py", line 651, in in6_isincluded
    temp = inet_pton(socket.AF_INET6, addr)
  File "/usr/local/lib/python2.7/dist-packages/scapy/pton_ntop.py", line 40, in inet_pton
    raise Exception("Illegal syntax for IP address")
Exception: Illegal syntax for IP address

**Comment by jakuta-tech** [comment]
@rainmansy mitmf isn't installed properly because it works fine.  Check the requirements and do a pip freeze and compare the output to other posts here for version information.  Most likely you have an incorrect version of a package .

`root@e99ku73e:~# mitmf --arp --spoof --target 192.168.15.49 --gateway 192.168.12.1 -i wlan0

███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗  
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online
`

**Comment by byt3bl33d3r** [comment]
^^ what he/she said. Closing.
