### ISSUE TITLE
from twisted.internet import reactor - After Updating Kali

### ISSUE THREAD

**Issue by spyder-7** [byt3bl33d3r/MITMf#374]
Just ran apt-get update, upgrade and dist-upgrade and after that mitmf stop working with the following error:
Traceback (most recent call last):
  File "./mitmf.py", line 33, in <module>
    from twisted.internet import reactor
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 41, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Where as it was working absolutely fine before update.

I already tried the install instruction and same error also all the requirements are already met.

Any help.

**Comment by JoeNibe** [comment]
Hey I had the same problem but I figured it out. Run the following in your terminal
`source /etc/bash_completion.d/virtualenvwrapper`
`mkvirtualenv MITMf -p /usr/bin/python2.7`
`./mitmf.py`

Thats it.It works. Hope it helps....
