### ISSUE TITLE
mitmf run error

### ISSUE THREAD

**Issue by minitehnicus** [byt3bl33d3r/MITMf#375]
Hello! I followed the installation instructions but i receive this error:

> Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/screenshotter.py", line 27, in <module>
    from plugins.inject import Inject
  File "/usr/share/mitmf/plugins/inject.py", line 24, in <module>
    from bs4 import BeautifulSoup
  File "build/bdist.linux-x86_64/egg/bs4/__init__.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/__init__.py", line 314, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/_html5lib.py", line 70, in <module>
AttributeError: 'module' object has no attribute '_base'

Thanks!

**Comment by Ritiek** [comment]
Seems like there is some problem with BeautifulSoup. Try reinstalling it..
`sudo pip uninstall BeautifulSoup4`
`sudo pip install BeautifulSoup4`
