### ISSUE TITLE
command requirement.text is not working

### ISSUE THREAD

**Issue by saikumar100** [byt3bl33d3r/MITMf#377]
Hi,
  After we enter this command in the terminal, I am getting this error
 pip install -r requirements.txt
    Collecting git+git://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
    Cloning git://github.com/kti/python-netfilterqueue to /tmp/pip-7L3G4c-build
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection timed out
github.com[1: 192.30.253.112]: errno=Connection timed out
github.com[2: 64:ff9b::c01e:fd71]: errno=Network is unreachable
github.com[3: 64:ff9b::c01e:fd70]: errno=Network is unreachable

Command "git clone -q git://github.com/kti/python-netfilterqueue /tmp/pip-7L3G4c-build" failed with error code 128 in None

Thanks,
Nick

**Comment by Ritiek** [comment]
Are you able to browse websites on that PC?

It says you got a network problem.

**Comment by saikumar100** [comment]
Yes! I am able to browse internet successfully.

**Comment by saikumar100** [comment]
Now,
when open python mitmf.py  , it is showing the below one:
[-]The derp is strong with this one

**Comment by saikumar100** [comment]
Hi, I got this issue when using sudoer with mitmf
sudo ./mitmf.py 
Traceback (most recent call last):
  File "./mitmf.py", line 33, in <module>
    from twisted.internet import reactor
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'

**Comment by byt3bl33d3r** [comment]
You obviously have network connectivity issues. Closing
