### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by himanshuyadav12345** [byt3bl33d3r/MITMf#388]
Hello 
I am using Kali linux and i install MITMF.
``` 
root@kali:~# sudo apt-get install mitmf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mitmf is already the newest version (0.9.8-0kali1).
The following packages were automatically installed and are no longer required:
  empathy empathy-common geoclue-2.0 gnome-dictionary gnome-screenshot
  gstreamer1.0-nice libchamplain-gtk-0.12-0 libfarstream-0.2-5 libgadu3
  libgdict-1.0-10 libgdict-common libgupnp-igd-1.0-4
  libjavascriptcoregtk-3.0-0 libmeanwhile1 libmission-control-plugins0
  libnice10 libprotobuf-c1 libpurple-bin libpurple0
  libtelepathy-farstream3 libwebkitgtk-3.0-0 libzephyr4
  linux-image-4.9.0-kali1-amd64 pidgin-data telepathy-gabble
  telepathy-haze telepathy-logger telepathy-mission-control-5
  telepathy-salut
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
I get this output. 
And After i ran mitm in terminal 
```
root@kali:~# mitmf
Traceback (most recent call last):
  File "./mitmf.py", line 32, in <module>
    from twisted.web import http
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/web/http.py", line 30, in <module>
    from twisted.internet import interfaces, reactor, protocol, address
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/internet/reactor.py", line 37, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/internet/default.py", line 50, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.pollreactor import install
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/internet/pollreactor.py", line 23, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 23, in <module>
    from twisted.internet import tcp, udp
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 27, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/internet/_newtls.py", line 20, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/Twisted-12.0.0-py2.7-linux-x86_64.egg/twisted/protocols/tls.py", line 39, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```
I get this error. 
My Linux Information is given below 
```
root@kali:~# uname -a
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.16-1kali1 (2017-03-24) x86_64 GNU/Linux
```
Please Help me to solve this problem. @
As soon as possible.
Thanks

**Comment by byt3bl33d3r** [comment]
That seems like a Kali packaging issue to me. You should open a bug report in the Kali bug tracker not here.

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
