### ISSUE TITLE
I dont know why it is not working...

### ISSUE THREAD

**Issue by adik69** [byt3bl33d3r/MITMf#390]
root@kali:~# cd MITMf/
root@kali:~/MITMf# sudo python mitmf.py 
Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/MITMf/plugins/upsidedownternet.py", line 21, in <module>
    from PIL import Image, ImageFile
  File "/usr/lib/python2.7/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: /usr/lib/python2.7/site-packages/PIL/_imaging.so: undefined symbol: PyUnicodeUCS2_AsLatin1String
root@kali:~/MITMf#

**Comment by byt3bl33d3r** [comment]
Closing since you didn't follow the guidelines for submitting a bug report. Please see the wiki [here](https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug) on how to properly report a bug.
