### ISSUE TITLE
The dreaded [Error 98]

### ISSUE THREAD

**Issue by Dontbemadpls** [byt3bl33d3r/MITMf#430]
So when I run
`python mitmf.py -i wlan0 --spoof --arp --hsts --dns --gateway 192.168.1.1 --target 192.168.1.34
`

I get this error:

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|_ Spoof v0.6
|  |_ DNS spoofing enabled
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
Error starting HTTP server: [Errno 98] Address already in use
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

I've tried checking netstat -pant to find a process using that port but to no avail...

`Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8123          0.0.0.0:*               LISTEN      506/polipo          
tcp        0      0 192.168.1.44:39442      172.217.23.130:443      ESTABLISHED 1870/firefox-esr    
tcp        0      0 192.168.1.44:53526      192.30.253.113:443      TIME_WAIT   -                   
tcp        0      0 192.168.1.44:48234      216.58.207.131:443      ESTABLISHED 1870/firefox-esr    
tcp        0      0 192.168.1.44:44782      52.2.140.86:443         ESTABLISHED 1870/firefox-esr    
tcp        0      0 192.168.1.44:42466      172.217.22.174:443      ESTABLISHED 1870/firefox-esr    
tcp        0      0 192.168.1.44:52610      172.217.18.3:443        ESTABLISHED 1870/firefox-esr    
tcp        0      0 192.168.1.44:58850      192.30.253.125:443      ESTABLISHED 1870/firefox-esr    
tcp        0      0 192.168.1.44:52072      172.217.18.14:443       ESTABLISHED 1870/firefox-esr    
tcp        0      0 192.168.1.44:58778      192.30.253.125:443      ESTABLISHED 1870/firefox-esr    
tcp6       0      0 :::80                   :::*                    LISTEN      1792/apache2     `

Reinstalled MITMf and got the exact same error. Reinstalled requirements. Updated kali. I'm at a loss.

**Comment by zu3s** [comment]
so when i type mitmf i get this...

Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/screenshotter.py", line 27, in <module>
    from plugins.inject import Inject
  File "/usr/share/mitmf/plugins/inject.py", line 24, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
