### ISSUE TITLE
Loading Issue (Most Likely With Python)

### ISSUE THREAD

**Issue by BaconBombz** [byt3bl33d3r/MITMf#455]
I Get this code everytime I run ~#python mitmf.py *whaterver other than --help.

 Traceback (most recent call last):
  File "mitmf.py", line 75, in <module>
    from core.utils import get_ip, get_mac, shutdown
  File "/root/MITMf/core/utils.py", line 27, in <module>
    from scapy.all import get_if_addr, get_if_hwaddr, get_working_if
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by gpotter2** [comment]
Update scapy to 2.4.0, fixes the problem
