### ISSUE TITLE
HEELP my

### ISSUE THREAD

**Issue by warese32** [byt3bl33d3r/MITMf#457]
помогите пожалуйста кто нибудь непонимаю в чем причина до переустоновки системы все работало ставил так же ту же систему но mitmf работать отказывается 
после запуска с root правами выдает мне следующие 

Traceback (most recent call last):
  File "mitmf.py", line 29, in <module>
    import core.responder.settings as settings
  File "/home/crystal/MITMf/core/responder/settings.py", line 24, in <module>
    from core.configwatcher import ConfigWatcher
  File "/home/crystal/MITMf/core/configwatcher.py", line 20, in <module>
    import pyinotify
ImportError: No module named pyinotify

**Comment by warese32** [comment]
помогите пожалуйста кто нибудь непонимаю в чем причина до переустоновки системы все работало ставил так же ту же систему но mitmf работать отказывается 
после запуска с root правами выдает мне следующие 

Traceback (most recent call last):
  File "mitmf.py", line 29, in <module>
    import core.responder.settings as settings
  File "/home/crystal/MITMf/core/responder/settings.py", line 24, in <module>
    from core.configwatcher import ConfigWatcher
  File "/home/crystal/MITMf/core/configwatcher.py", line 20, in <module>
    import pyinotify
ImportError: No module named pyinotify

**Comment by byt3bl33d3r** [comment]
no
