### ISSUE TITLE
mitmf not working

### ISSUE THREAD

**Issue by girishbhagwani** [byt3bl33d3r/MITMf#478]
|/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

Traceback (most recent call last):
  File "./mitmf.py", line 80, in <module>
    from core.netcreds import NetCreds
  File "/usr/share/mitmf/core/netcreds.py", line 17, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function
![screenshot from 2018-05-24 21-48-58](https://user-images.githubusercontent.com/28143456/40498310-5349292c-5f9c-11e8-87f6-4dad12021db4.png)
![screenshot from 2018-05-24 21-48-58](https://user-images.githubusercontent.com/28143456/40498414-9d8f33aa-5f9c-11e8-9345-e4dbde49577d.png)

**Comment by K410** [comment]
dud, follow these steps https://github.com/byt3bl33d3r/MITMf/wiki/installation
