### ISSUE TITLE
Unhandled Error Traceback

### ISSUE THREAD

**Issue by bmb9** [byt3bl33d3r/MITMf#488]
[*] MITMf v0.9.8 - 'The Dark Side'
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ JSKeylogger v0.2
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Serving Flask app "core.mitmfapi" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
|_ HTTP server online
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ DNSChef v0.4 online
|_ SMB server online

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 602, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 587, in doConnect
    self._connectDone()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 616, in _connectDone
    self.protocol.makeConnection(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 494, in makeConnection
    self.connectionMade()
  File "/usr/share/mitmf/core/sslstrip/ServerConnection.py", line 108, in connectionMade
    user_agent = parse(self.headers['user-agent'])
  File "/usr/lib/python2.7/dist-packages/user_agents/parsers.py", line 254, in parse
    return UserAgent(user_agent_string)
  File "/usr/lib/python2.7/dist-packages/user_agents/parsers.py", line 139, in __init__
    self.device = parse_device(**ua_dict['device'])
exceptions.TypeError: parse_device() takes exactly 3 arguments (1 given)

**Comment by evanotone** [comment]
same problem
any body know this issue!!? help

**Comment by kamiine** [comment]
same problem

**Comment by etcshadow1** [comment]
Just remember when installing to not have apache2 or any other services running. Also you will want to install "pip install twisted==15.5.0" This should resolve all your issues.
