### ISSUE TITLE
MITMf not working

### ISSUE THREAD

**Issue by mehdi666hoseini** [byt3bl33d3r/MITMf#489]
mitmf is not working
for example when I run this : 
`mitmf -i eth0 --spoof --arp --gateway 172.16.2.1 --target 172.16.2.28 --inject --js-payload "alert(1);"`

i get : 
```
[*] MITMf v0.9.8 - 'The Dark Side'
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Serving Flask app "core.mitmfapi" (lazy loading)
Error starting HTTP server: [Errno 98] Address already in use
|_ HTTP server online
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ DNSChef v0.4 online
|_ SMB server online




Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'

```

**Comment by mehdi666hoseini** [comment]
by the way, i'm using the version that is pre-installed on kali 2018.2

**Comment by mehdi666hoseini** [comment]
also, when is use the github version, i get this:

`Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/Desktop/MITMf-master/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
ImportError: No module named bdfactory
`
