### ISSUE TITLE
MITMf Error while launching it  .. 

### ISSUE THREAD

**Issue by amitkurud** [byt3bl33d3r/MITMf#49]
mitmf doesnt launches 
 ```
Traceback (most recent call last):
  File "./mitmf.py", line 23, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/SMBAuth.py", line 2, in <module>
    from plugins.Inject import Inject
  File "/usr/share/mitmf/plugins/Inject.py", line 3, in <module>
    from scapy.all import get_if_addr
  File "/usr/lib/python2.7/dist-packages/scapy/all.py", line 25, in <module>
    from route import *
  File "/usr/lib/python2.7/dist-packages/scapy/route.py", line 162, in <module>
    conf.route=Route()
  File "/usr/lib/python2.7/dist-packages/scapy/route.py", line 22, in __init__
    self.resync()
  File "/usr/lib/python2.7/dist-packages/scapy/route.py", line 31, in resync
    self.routes = read_routes()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 151, in read_routes
    ifreq = ioctl(s, SIOCGIFADDR,struct.pack("16s16x",LOOPBACK_NAME))
IOError: [Errno 99] Cannot assign requested address
```
Tried installing both repo and git  on kali 64

**Comment by byt3bl33d3r** [comment]
@amitkurud can you please give me the full command string you used?

**Comment by amitkurud** [comment]
I just used ./mitmf.py nothing else

**Comment by byt3bl33d3r** [comment]
@amitkurud what OS are you using?

**Comment by amitkurud** [comment]
Kali... By the way It is now running . Like YOu said Problem was In my
/etc/networking/interfaces. Thanks
