### ISSUE TITLE
MITMf on BlackArch

### ISSUE THREAD

**Issue by 18Rules** [byt3bl33d3r/MITMf#60]
I can't launch MITMF on BlackArh, I always get this message:

Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/Spoof.py", line 28, in <module>
    from libs.dnschef.dnschef import DNSChef
ImportError: No module named dnschef.dnschef

**Comment by byt3bl33d3r** [comment]
@18Rules are you using the 'git' version or the one in their repos?

**Comment by 18Rules** [comment]
I get the same message with both versions, I'm I doing something wrong?

**Comment by byt3bl33d3r** [comment]
yes, please refer to the readme for installation instructions. 
In the meantime I'll try to contact the blackarch devs, because if you get the same error with the repo version it means that they packaged it wrong

**Comment by Fedga** [comment]
i am using the git version and i have the same problem
Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
ImportError: No module named bdfactory

**Comment by aldaheyah** [comment]
me too ..

**Comment by febritecno** [comment]
me too.. T_T
Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/home/febritecno/custom/MITMF/plugins/smbauth.py", line 22, in <module>
    from plugins.inject import Inject
  File "/home/febritecno/custom/MITMF/plugins/inject.py", line 22, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by Valak77133** [comment]
Traceback (most recent call last):
  File "./mitmf.py", line 36, in <module>
    from plugins import *
  File "/usr/share/mitmf/plugins/filepwn.py", line 72, in <module>
    from libs.bdfactory import pebin
ImportError: No module named bdfactory
