### ISSUE TITLE
Error to import ipy and error for ua-parser and for socket

### ISSUE THREAD

**Issue by Nyzo** [byt3bl33d3r/MITMf#65]
Add ipy to requirements.txt and an error displayed:
```sh
Traceback (most recent call last):
  File "mitmf.py", line 41, in <module>
    import user_agents
  File "/usr/local/lib/python2.7/dist-packages/user_agents/__init__.py", line 3, in <module>
    from .parsers import parse
  File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 4, in <module>
    from ua_parser import user_agent_parser
  File "/usr/local/lib/python2.7/dist-packages/ua_parser-0.4.0-py2.7.egg/ua_parser/user_agent_parser.py", line 460, in <module>
    yamlFile = open(yamlPath)
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/ua_parser-0.4.0-py2.7.egg/ua_parser/regexes.yaml'
```

Second error:
```sh
Traceback (most recent call last):
  File "mitmf.py", line 187, in <module>
    DNSChef.getInstance().startUDP()
  File "/etc/MITMf/libs/dnschef/dnschef.py", line 473, in startUDP
    server = ThreadedUDPServer((self.server_address, int(self.port)), UDPHandler)
  File "/etc/MITMf/libs/dnschef/dnschef.py", line 402, in __init__
    SocketServer.UDPServer.__init__(self,server_address,RequestHandlerClass) 
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

**Comment by byt3bl33d3r** [comment]
I don't understand.. you added ipy to the requirements?

**Comment by byt3bl33d3r** [comment]
@Nyzo the first error is because something's wrong with youre user_agents library, try re-installing it.
the second error is because your running a service on port 53, so MITMf can't bind to it.

**Comment by Nyzo** [comment]
@byt3bl33d3r for the first error, i find a solution that works : pip install -e git+git://github.com/selwin/ua-parser.git#egg=ua-parser
For the second I'll try to find a solution, thanks!

**Comment by byt3bl33d3r** [comment]
@Nyzo ok cool, since I've been getting multiple emails regarding the second error , I'll add in some error handeling to make it as clear as possible

**Comment by byt3bl33d3r** [comment]
@Nyzo I'm closing the issue in the meantime

**Comment by Nyzo** [comment]
Ok, i run this command **netstat -tulpn | grep :** and i find that for pid/program:
2721/dnsmasq
It's normally? Not dangerous to kill this?
