### ISSUE TITLE
Upsidedownternet seems broken

### ISSUE THREAD

**Issue by 0x42424242** [byt3bl33d3r/MITMf#71]
I was testing out upsidedownternet (along with all the other features) and it seems the python scripting for it is broken. Visiting HTTP sites I only get failed loading of pictures, and the following the log being displayed within the console (one for each picture). 

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 586, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 199, in doRead
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 564, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 448, in lineReceived
    self.extractHeader(self._header)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 407, in extractHeader
    self.handleHeader(key, val)
  File "/usr/share/mitmf/libs/sslstrip/ServerConnection.py", line 158, in handleHeader
    self.plugins.hook()
  File "/usr/share/mitmf/libs/sergioproxy/ProxyPlugins.py", line 82, in hook
    a = f(**args)
  File "/usr/share/mitmf/plugins/Upsidedownternet.py", line 25, in handleHeader
    request.imageType = value.split("/")[1].upper()
exceptions.IndexError: list index out of range

```

System Information
```
Attacking OS: Kali
Version: mitmf 0.9

Victim OS: OS X
Browser: Firefox 37.0
```

**Comment by byt3bl33d3r** [comment]
@0x42424242 Kali has a very old version of MITMf in their repos currently , this bug was fixed a while ago. Your probably going to want to get MITMf directly from github, you can find the installation instructions in the README.md

**Comment by 0x42424242** [comment]
Thanks for that mate, I apologise for raising a issue which was already resolved. Github version here I come :)

**Comment by byt3bl33d3r** [comment]
@0x42424242 np man, find anything wonky in the new version just le me know
