### ISSUE TITLE
user_agents library missing

### ISSUE THREAD

**Issue by anandumdas** [byt3bl33d3r/MITMf#75]
Installed mitmf added dependencies and ran as sudo. Shows the error `user_agents library missing! User-Agent parsing will be disabled!`

**Comment by byt3bl33d3r** [comment]
Please refer to the readme to install the required dependencies

**Comment by anandumdas** [comment]
I have installed all Python dependencies. Still the issue exists. Ubuntu 14.04

**Comment by byt3bl33d3r** [comment]
@anandumdas can you paste the output of ```pip freeze```?

**Comment by anandumdas** [comment]
Output of `pip freeze`

```
BeautifulSoup==3.2.1
GeoIP-Python==1.2.4
GitPython==0.3.2.RC1
IPy==0.83
PAM==0.4.2
Pillow==2.3.0
PyGithub==1.21.0
PyYAML==3.11
Pygments==1.6
Twisted==10.2.0
Twisted-Core==13.2.0
Twisted-Web==13.2.0
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
argparse==1.2.1
async==0.6.1
capstone==3.0.2
ccsm==0.9.11.2
chardet==2.1.1
clamd==1.0.1
cluster==1.1.1b3
colorama==0.2.5
command-not-found==0.3
compizconfig-python==0.9.11.2
configobj==5.0.6
darts.util.lru==0.5
debtagshw==0.1
defer==1.0.6
dirspec==13.10
dnslib==0.9.4
dnspython==1.11.1
drozer==2.3.3
duplicity==0.6.23
esmre==0.3.1
gitdb==0.5.4
guess-language==0.2
halberd==0.2.4
html5lib==0.999
httpie==0.8.0
httplib2==0.8
lockfile==0.8
lxml==2.3.2
msgpack-python==0.2.4
netifaces==0.8
nltk==2.0.4
oauthlib==0.6.1
oneconf==0.3.7
pdfminer==20110515
pefile==1.2.10-114
pexpect==3.1
phply==0.9.1
piston-mini-client==0.7.5
ply==3.4
protobuf==2.4.1
py-pypcap==1.1.2
pyOpenSSL==0.13
pybloomfiltermmap==0.3.11
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pygobject==3.12.0
pyserial==2.6
pysmbc==1.0.14.1
python-apt==0.9.3.5
python-debian==0.1.21-nmu2ubuntu2
python-ntlm==1.0.1
python-socksipy==1.0
pyxdg==0.25
reportlab==3.0
requests==2.2.1
scapy==2.2.0
scapy-real==2.2.0-dev
sessioninstaller==0.0.0
six==1.5.2
smmap==0.8.2
software-center-aptd-plugins==0.0.0
ssh-import-id==3.21
system-service==0.1.6
unity-lens-photos==1.0
urllib3==1.7.1
vboxapi==1.0
wsgiref==0.1.2
xdiagnose==3.6.3build2
xdot==0.6
zope.interface==4.0.5
```

**Comment by byt3bl33d3r** [comment]
@anandumdas as you can see your missing the ```user-agents``` package... Follow the instructions in the Readme to install it

**Comment by anandumdas** [comment]
@byt3bl33d3r I have manually installed all the dependencies mentioned in the requirements file. Reinstalled mitmf as explained in readme. Now when I run `sudo ./mitmf -i eth7` (eth7 is my interface), sadly, I get the following error.

```
Traceback (most recent call last):
  File "./mitmf.py", line 187, in <module>
    DNSChef.getInstance().startUDP()
  File "/home/username/Desktop/MITMf/libs/dnschef/dnschef.py", line 473, in startUDP
    server = ThreadedUDPServer((self.server_address, int(self.port)), UDPHandler)
  File "/home/username/Desktop/MITMf/libs/dnschef/dnschef.py", line 402, in __init__
    SocketServer.UDPServer.__init__(self,server_address,RequestHandlerClass) 
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

**Comment by byt3bl33d3r** [comment]
@anandumdas MITMf has a DNS server that binds to port 53...It seems that you have a running service that is currently using that port (probably dnsmasq), so to use MITMf you just have to disable it

**Comment by anandumdas** [comment]
I disabled dnsmasq on port 53 by the command `sudo dnsmasq -p 0`. Error still exists. Can you please tell me which all ports are used by mitmf so that I could check them explicitly.

**Comment by byt3bl33d3r** [comment]
Currently only port 53 is used

**Comment by c0mandante** [comment]
@anandumdas you have to disable dnsmasq in the NetworkManager config
/etc/NetworkManager/NetworkManager.conf
[main]
plugins=ifupdown,keyfile,ofono
#dns=dnsmasq <== to comment

[ifupdown]
managed=false

**Comment by tricheco85** [comment]
service dnsmasq stop

but the client is client disconnected after.

hostapd + dnsmasq for FAKE AP and use MITMF for sniffing.
