### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by dash00** [byt3bl33d3r/MITMf#80]
Hi,
I get an error while following the installation guidelines (from source) :

```
$ pip install -r requirements.txt
[...]

Downloading/unpacking pypcap (from -r requirements.txt (line 17))
  Running setup.py egg_info for package pypcap
    Found pcap headers in /usr/src/linux-headers-3.13.0-35-generic/include/config/ezx/pcap.h
    Found libraries in None
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/dash/local/projects/security/MITMf/build/pypcap/setup.py", line 61, in <module>
        lib_file = os.path.basename(lib_file_path)
      File "/usr/lib/python2.7/posixpath.py", line 112, in basename
        i = p.rfind('/') + 1
    AttributeError: 'NoneType' object has no attribute 'rfind'
    Complete output from command python setup.py egg_info:
    Found pcap headers in /usr/src/linux-headers-3.13.0-35-generic/include/config/ezx/pcap.h

Found libraries in None

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/dash/local/projects/security/MITMf/build/pypcap/setup.py", line 61, in <module>

    lib_file = os.path.basename(lib_file_path)

  File "/usr/lib/python2.7/posixpath.py", line 112, in basename

    i = p.rfind('/') + 1

AttributeError: 'NoneType' object has no attribute 'rfind'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/dash/.pip/pip.log
```

**Comment by byt3bl33d3r** [comment]
Hi,
This is a problem with ```pypcap``` , not ```MITMf```.. in any case what OS are you using? did you try installing ```pypcap```via your distros repos?

**Comment by byt3bl33d3r** [comment]
@dash00 I'm closing the issue since it really isn't related to the framework, feel free to comment below and I'll try to help as much as i can

**Comment by dash00** [comment]
Thanks for your help
I'm trying to install on Ubuntu 12.04 (x64), I haven't got Kali installed yet. 
I just tried to install `python-pypcap` (which was not installed at the first try) from dist repo but the error remains..

**Comment by byt3bl33d3r** [comment]
@dash00 If you installed ```python-pypcap``` from your distros repos, you don't need to install it via ```pip``` anymore, try running MITMf to see if it finds it

**Comment by dash00** [comment]
Great ! I removed pypcap from requirements.txt and it went to the end of the installation process. MITMf runs without error now. Thanks a lot

**Comment by byt3bl33d3r** [comment]
@dash00 np!
