### ISSUE TITLE
issue with -c switch!

### ISSUE THREAD

**Issue by zphinx** [byt3bl33d3r/MITMf#81]
Traceback (most recent call last):
  File "mitmf.py", line 111, in <module>
    config_args = configfile['MITMf']['args']
  File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'MITMf'

while executing mitmf with the -c switch

**Comment by byt3bl33d3r** [comment]
@zphinx hey man, 
seems you are specifying a corrupted config file with the c switch.. If you can pastebin it i'll take a look
